//! DiscussChannel trigger handlers
//!
//! Auto-generated by backbone-cli. Do not edit manually.

use std::sync::Arc;
use async_trait::async_trait;
use backbone_core::trigger::{
    ActionExecutor, TriggerContext, TriggerContextMut, TriggerEvent, TriggerHandler, TriggerRegistry,
};

use crate::domain::entity::DiscussChannel;

pub type DiscussChannelTriggerEvent      = TriggerEvent;
pub type DiscussChannelTriggerContext    = TriggerContext<DiscussChannel>;
pub type DiscussChannelTriggerContextMut = TriggerContextMut<DiscussChannel>;
pub type DiscussChannelActionExecutor    = ActionExecutor;
pub type DiscussChannelTriggerRegistry   = TriggerRegistry<DiscussChannel>;
pub type DiscussChannelTriggerHandlerObj =
    dyn TriggerHandler<TriggerContext<DiscussChannel>, TriggerEvent>;

/// Create a default registry pre-populated with all handlers for DiscussChannel.
pub fn discuss_channel_trigger_registry() -> DiscussChannelTriggerRegistry {
    TriggerRegistry::build(|r| {
    })
}
