//! MailActivityType trigger handlers
//!
//! Auto-generated by backbone-cli. Do not edit manually.

use std::sync::Arc;
use async_trait::async_trait;
use backbone_core::trigger::{
    ActionExecutor, TriggerContext, TriggerContextMut, TriggerEvent, TriggerHandler, TriggerRegistry,
};

use crate::domain::entity::MailActivityType;

pub type MailActivityTypeTriggerEvent      = TriggerEvent;
pub type MailActivityTypeTriggerContext    = TriggerContext<MailActivityType>;
pub type MailActivityTypeTriggerContextMut = TriggerContextMut<MailActivityType>;
pub type MailActivityTypeActionExecutor    = ActionExecutor;
pub type MailActivityTypeTriggerRegistry   = TriggerRegistry<MailActivityType>;
pub type MailActivityTypeTriggerHandlerObj =
    dyn TriggerHandler<TriggerContext<MailActivityType>, TriggerEvent>;

// State machine trigger handlers

/// Create a default registry pre-populated with all handlers for MailActivityType.
pub fn mail_activity_type_trigger_registry() -> MailActivityTypeTriggerRegistry {
    TriggerRegistry::build(|r| {
    })
}

