//! MailActivity trigger handlers
//!
//! Auto-generated by backbone-cli. Do not edit manually.

use std::sync::Arc;
use async_trait::async_trait;
use backbone_core::trigger::{
    ActionExecutor, TriggerContext, TriggerContextMut, TriggerEvent, TriggerHandler, TriggerRegistry,
};

use crate::domain::entity::MailActivity;

pub type MailActivityTriggerEvent      = TriggerEvent;
pub type MailActivityTriggerContext    = TriggerContext<MailActivity>;
pub type MailActivityTriggerContextMut = TriggerContextMut<MailActivity>;
pub type MailActivityActionExecutor    = ActionExecutor;
pub type MailActivityTriggerRegistry   = TriggerRegistry<MailActivity>;
pub type MailActivityTriggerHandlerObj =
    dyn TriggerHandler<TriggerContext<MailActivity>, TriggerEvent>;

/// Create a default registry pre-populated with all handlers for MailActivity.
pub fn mail_activity_trigger_registry() -> MailActivityTriggerRegistry {
    TriggerRegistry::build(|r| {
    })
}
