//! MailBlacklist trigger handlers
//!
//! Auto-generated by backbone-cli. Do not edit manually.

use std::sync::Arc;
use async_trait::async_trait;
use backbone_core::trigger::{
    ActionExecutor, TriggerContext, TriggerContextMut, TriggerEvent, TriggerHandler, TriggerRegistry,
};

use crate::domain::entity::MailBlacklist;

pub type MailBlacklistTriggerEvent      = TriggerEvent;
pub type MailBlacklistTriggerContext    = TriggerContext<MailBlacklist>;
pub type MailBlacklistTriggerContextMut = TriggerContextMut<MailBlacklist>;
pub type MailBlacklistActionExecutor    = ActionExecutor;
pub type MailBlacklistTriggerRegistry   = TriggerRegistry<MailBlacklist>;
pub type MailBlacklistTriggerHandlerObj =
    dyn TriggerHandler<TriggerContext<MailBlacklist>, TriggerEvent>;

/// Create a default registry pre-populated with all handlers for MailBlacklist.
pub fn mail_blacklist_trigger_registry() -> MailBlacklistTriggerRegistry {
    TriggerRegistry::build(|r| {
    })
}
