//! MailFollowers trigger handlers
//!
//! Auto-generated by backbone-cli. Do not edit manually.

use std::sync::Arc;
use async_trait::async_trait;
use backbone_core::trigger::{
    ActionExecutor, TriggerContext, TriggerContextMut, TriggerEvent, TriggerHandler, TriggerRegistry,
};

use crate::domain::entity::MailFollowers;

pub type MailFollowersTriggerEvent      = TriggerEvent;
pub type MailFollowersTriggerContext    = TriggerContext<MailFollowers>;
pub type MailFollowersTriggerContextMut = TriggerContextMut<MailFollowers>;
pub type MailFollowersActionExecutor    = ActionExecutor;
pub type MailFollowersTriggerRegistry   = TriggerRegistry<MailFollowers>;
pub type MailFollowersTriggerHandlerObj =
    dyn TriggerHandler<TriggerContext<MailFollowers>, TriggerEvent>;

/// Create a default registry pre-populated with all handlers for MailFollowers.
pub fn mail_followers_trigger_registry() -> MailFollowersTriggerRegistry {
    TriggerRegistry::build(|r| {
    })
}

