//! Sms trigger handlers
//!
//! Auto-generated by backbone-cli. Do not edit manually.

use std::sync::Arc;
use async_trait::async_trait;
use backbone_core::trigger::{
    ActionExecutor, TriggerContext, TriggerContextMut, TriggerEvent, TriggerHandler, TriggerRegistry,
};

use crate::domain::entity::Sms;

pub type SmsTriggerEvent      = TriggerEvent;
pub type SmsTriggerContext    = TriggerContext<Sms>;
pub type SmsTriggerContextMut = TriggerContextMut<Sms>;
pub type SmsActionExecutor    = ActionExecutor;
pub type SmsTriggerRegistry   = TriggerRegistry<Sms>;
pub type SmsTriggerHandlerObj =
    dyn TriggerHandler<TriggerContext<Sms>, TriggerEvent>;

// State machine trigger handlers

/// Create a default registry pre-populated with all handlers for Sms.
pub fn sms_trigger_registry() -> SmsTriggerRegistry {
    TriggerRegistry::build(|r| {
    })
}
