//! MailGatewayAllowed DTOs (Data Transfer Objects)
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc};

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::MailGatewayAllowed;
use crate::domain::entity::AuditMetadata;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new MailGatewayAllowed
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreateMailGatewayAllowedDto {
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "fetchmail_server_id")]
    pub fetchmail_server_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub pattern: String,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub active: bool,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a MailGatewayAllowed
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdateMailGatewayAllowedDto {
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "fetchmail_server_id")]
    pub fetchmail_server_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub pattern: String,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub active: bool,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a MailGatewayAllowed
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchMailGatewayAllowedDto {
    #[serde(skip_serializing_if = "Option::is_none", alias = "fetchmail_server_id")]
    pub fetchmail_server_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub pattern: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub active: Option<bool>,
}

impl PatchMailGatewayAllowedDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.fetchmail_server_id.is_some() || self.pattern.is_some() || self.active.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for MailGatewayAllowed entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct MailGatewayAllowedResponseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub id: Uuid,
    pub fetchmail_server_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub pattern: String,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub active: bool,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for MailGatewayAllowed entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct MailGatewayAllowedListResponseDto {
    /// List of items
    pub items: Vec<MailGatewayAllowedResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl MailGatewayAllowedListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<MailGatewayAllowedResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct MailGatewayAllowedSummaryDto {
    pub id: Uuid,
    pub fetchmail_server_id: Option<Uuid>,
    pub pattern: String,
    pub active: bool,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<MailGatewayAllowed> for MailGatewayAllowedResponseDto {
    fn from(entity: MailGatewayAllowed) -> Self {
        Self {
            id: entity.id,
            fetchmail_server_id: entity.fetchmail_server_id,
            pattern: entity.pattern,
            active: entity.active,
            metadata: entity.metadata,
        }
    }
}

impl From<MailGatewayAllowed> for MailGatewayAllowedSummaryDto {
    fn from(entity: MailGatewayAllowed) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            fetchmail_server_id: entity.fetchmail_server_id,
            pattern: entity.pattern,
            active: entity.active,
            created_at,
        }
    }
}

impl From<CreateMailGatewayAllowedDto> for MailGatewayAllowed {
    fn from(dto: CreateMailGatewayAllowedDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            fetchmail_server_id: dto.fetchmail_server_id,
            pattern: dto.pattern,
            active: dto.active,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&MailGatewayAllowed> for MailGatewayAllowedResponseDto {
    fn from(entity: &MailGatewayAllowed) -> Self {
        Self {
            id: entity.id.clone(),
            fetchmail_server_id: entity.fetchmail_server_id.clone(),
            pattern: entity.pattern.clone(),
            active: entity.active.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreateMailGatewayAllowedDto> for MailGatewayAllowed {
    fn from_create_dto(dto: CreateMailGatewayAllowedDto) -> backbone_core::ServiceResult<Self> {
        Ok(MailGatewayAllowed::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdateMailGatewayAllowedDto> for MailGatewayAllowed {
    fn apply_update(mut self, dto: UpdateMailGatewayAllowedDto) -> backbone_core::ServiceResult<Self> {
        self.fetchmail_server_id = dto.fetchmail_server_id;
        self.pattern = dto.pattern;
        self.active = dto.active;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to MailGatewayAllowed here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs
