//! MailAlias DTOs (Data Transfer Objects)
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc};

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::MailAlias;
use crate::domain::entity::AuditMetadata;
use crate::domain::entity::MailAliasContact;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new MailAlias
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreateMailAliasDto {
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "alias_name")]
    pub alias_name: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "alias_domain_id")]
    pub alias_domain_id: Option<Uuid>,
    #[serde(alias = "alias_contact")]
    pub alias_contact: MailAliasContact,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "alias_model_id")]
    pub alias_model_id: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "alias_parent_model_id")]
    pub alias_parent_model_id: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "alias_parent_thread_id")]
    pub alias_parent_thread_id: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "alias_user_id")]
    pub alias_user_id: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "alias_defaults")]
    pub alias_defaults: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "alias_force_thread_id")]
    pub alias_force_thread_id: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "alias_reply_to_address")]
    pub alias_reply_to_address: Option<String>,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a MailAlias
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdateMailAliasDto {
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "alias_name")]
    pub alias_name: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "alias_domain_id")]
    pub alias_domain_id: Option<Uuid>,
    #[serde(alias = "alias_contact")]
    pub alias_contact: MailAliasContact,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "alias_model_id")]
    pub alias_model_id: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "alias_parent_model_id")]
    pub alias_parent_model_id: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "alias_parent_thread_id")]
    pub alias_parent_thread_id: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "alias_user_id")]
    pub alias_user_id: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "alias_defaults")]
    pub alias_defaults: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "alias_force_thread_id")]
    pub alias_force_thread_id: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "alias_reply_to_address")]
    pub alias_reply_to_address: Option<String>,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a MailAlias
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchMailAliasDto {
    #[serde(skip_serializing_if = "Option::is_none", alias = "alias_name")]
    pub alias_name: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "alias_domain_id")]
    pub alias_domain_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "alias_contact")]
    pub alias_contact: Option<MailAliasContact>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "alias_model_id")]
    pub alias_model_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "alias_parent_model_id")]
    pub alias_parent_model_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "alias_parent_thread_id")]
    pub alias_parent_thread_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "alias_user_id")]
    pub alias_user_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "alias_defaults")]
    pub alias_defaults: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "alias_force_thread_id")]
    pub alias_force_thread_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "alias_reply_to_address")]
    pub alias_reply_to_address: Option<String>,
}

impl PatchMailAliasDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.alias_name.is_some() || self.alias_domain_id.is_some() || self.alias_contact.is_some() || self.alias_model_id.is_some() || self.alias_parent_model_id.is_some() || self.alias_parent_thread_id.is_some() || self.alias_user_id.is_some() || self.alias_defaults.is_some() || self.alias_force_thread_id.is_some() || self.alias_reply_to_address.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for MailAlias entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct MailAliasResponseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub id: Uuid,
    pub alias_name: Option<String>,
    pub alias_domain_id: Option<Uuid>,
    pub alias_contact: MailAliasContact,
    pub alias_model_id: Option<Uuid>,
    pub alias_parent_model_id: Option<Uuid>,
    pub alias_parent_thread_id: Option<Uuid>,
    pub alias_user_id: Option<Uuid>,
    pub alias_defaults: Option<String>,
    pub alias_force_thread_id: Option<Uuid>,
    pub alias_reply_to_address: Option<String>,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for MailAlias entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct MailAliasListResponseDto {
    /// List of items
    pub items: Vec<MailAliasResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl MailAliasListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<MailAliasResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct MailAliasSummaryDto {
    pub id: Uuid,
    pub alias_name: Option<String>,
    pub alias_domain_id: Option<Uuid>,
    pub alias_contact: MailAliasContact,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<MailAlias> for MailAliasResponseDto {
    fn from(entity: MailAlias) -> Self {
        Self {
            id: entity.id,
            alias_name: entity.alias_name,
            alias_domain_id: entity.alias_domain_id,
            alias_contact: entity.alias_contact,
            alias_model_id: entity.alias_model_id,
            alias_parent_model_id: entity.alias_parent_model_id,
            alias_parent_thread_id: entity.alias_parent_thread_id,
            alias_user_id: entity.alias_user_id,
            alias_defaults: entity.alias_defaults,
            alias_force_thread_id: entity.alias_force_thread_id,
            alias_reply_to_address: entity.alias_reply_to_address,
            metadata: entity.metadata,
        }
    }
}

impl From<MailAlias> for MailAliasSummaryDto {
    fn from(entity: MailAlias) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            alias_name: entity.alias_name,
            alias_domain_id: entity.alias_domain_id,
            alias_contact: entity.alias_contact,
            created_at,
        }
    }
}

impl From<CreateMailAliasDto> for MailAlias {
    fn from(dto: CreateMailAliasDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            alias_name: dto.alias_name,
            alias_domain_id: dto.alias_domain_id,
            alias_contact: dto.alias_contact,
            alias_model_id: dto.alias_model_id,
            alias_parent_model_id: dto.alias_parent_model_id,
            alias_parent_thread_id: dto.alias_parent_thread_id,
            alias_user_id: dto.alias_user_id,
            alias_defaults: dto.alias_defaults,
            alias_force_thread_id: dto.alias_force_thread_id,
            alias_reply_to_address: dto.alias_reply_to_address,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&MailAlias> for MailAliasResponseDto {
    fn from(entity: &MailAlias) -> Self {
        Self {
            id: entity.id.clone(),
            alias_name: entity.alias_name.clone(),
            alias_domain_id: entity.alias_domain_id.clone(),
            alias_contact: entity.alias_contact.clone(),
            alias_model_id: entity.alias_model_id.clone(),
            alias_parent_model_id: entity.alias_parent_model_id.clone(),
            alias_parent_thread_id: entity.alias_parent_thread_id.clone(),
            alias_user_id: entity.alias_user_id.clone(),
            alias_defaults: entity.alias_defaults.clone(),
            alias_force_thread_id: entity.alias_force_thread_id.clone(),
            alias_reply_to_address: entity.alias_reply_to_address.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreateMailAliasDto> for MailAlias {
    fn from_create_dto(dto: CreateMailAliasDto) -> backbone_core::ServiceResult<Self> {
        Ok(MailAlias::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdateMailAliasDto> for MailAlias {
    fn apply_update(mut self, dto: UpdateMailAliasDto) -> backbone_core::ServiceResult<Self> {
        self.alias_name = dto.alias_name;
        self.alias_domain_id = dto.alias_domain_id;
        self.alias_contact = dto.alias_contact;
        self.alias_model_id = dto.alias_model_id;
        self.alias_parent_model_id = dto.alias_parent_model_id;
        self.alias_parent_thread_id = dto.alias_parent_thread_id;
        self.alias_user_id = dto.alias_user_id;
        self.alias_defaults = dto.alias_defaults;
        self.alias_force_thread_id = dto.alias_force_thread_id;
        self.alias_reply_to_address = dto.alias_reply_to_address;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to MailAlias here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs
