//! MailBlacklist DTOs (Data Transfer Objects)
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc};

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::MailBlacklist;
use crate::domain::entity::AuditMetadata;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new MailBlacklist
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreateMailBlacklistDto {
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub email: String,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub active: bool,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a MailBlacklist
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdateMailBlacklistDto {
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub email: String,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub active: bool,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a MailBlacklist
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchMailBlacklistDto {
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub email: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub active: Option<bool>,
}

impl PatchMailBlacklistDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.email.is_some() || self.active.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for MailBlacklist entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct MailBlacklistResponseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub email: String,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub active: bool,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for MailBlacklist entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct MailBlacklistListResponseDto {
    /// List of items
    pub items: Vec<MailBlacklistResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl MailBlacklistListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<MailBlacklistResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct MailBlacklistSummaryDto {
    pub id: Uuid,
    pub email: String,
    pub active: bool,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<MailBlacklist> for MailBlacklistResponseDto {
    fn from(entity: MailBlacklist) -> Self {
        Self {
            id: entity.id,
            email: entity.email,
            active: entity.active,
            metadata: entity.metadata,
        }
    }
}

impl From<MailBlacklist> for MailBlacklistSummaryDto {
    fn from(entity: MailBlacklist) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            email: entity.email,
            active: entity.active,
            created_at,
        }
    }
}

impl From<CreateMailBlacklistDto> for MailBlacklist {
    fn from(dto: CreateMailBlacklistDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            email: dto.email,
            active: dto.active,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&MailBlacklist> for MailBlacklistResponseDto {
    fn from(entity: &MailBlacklist) -> Self {
        Self {
            id: entity.id.clone(),
            email: entity.email.clone(),
            active: entity.active.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreateMailBlacklistDto> for MailBlacklist {
    fn from_create_dto(dto: CreateMailBlacklistDto) -> backbone_core::ServiceResult<Self> {
        Ok(MailBlacklist::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdateMailBlacklistDto> for MailBlacklist {
    fn apply_update(mut self, dto: UpdateMailBlacklistDto) -> backbone_core::ServiceResult<Self> {
        self.email = dto.email;
        self.active = dto.active;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to MailBlacklist here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs

