//! MailTrackingValue DTOs (Data Transfer Objects)
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc};

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::MailTrackingValue;
use crate::domain::entity::AuditMetadata;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new MailTrackingValue
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreateMailTrackingValueDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "mail_message_id")]
    pub mail_message_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub field: String,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "field_desc")]
    pub field_desc: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "field_type")]
    pub field_type: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "old_value_integer")]
    pub old_value_integer: Option<i32>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "old_value_float")]
    pub old_value_float: Option<f64>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "old_value_text")]
    pub old_value_text: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "old_value_datetime")]
    pub old_value_datetime: Option<DateTime<Utc>>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "new_value_integer")]
    pub new_value_integer: Option<i32>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "new_value_float")]
    pub new_value_float: Option<f64>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "new_value_text")]
    pub new_value_text: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "new_value_datetime")]
    pub new_value_datetime: Option<DateTime<Utc>>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "currency_id")]
    pub currency_id: Option<Uuid>,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a MailTrackingValue
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdateMailTrackingValueDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "mail_message_id")]
    pub mail_message_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub field: String,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "field_desc")]
    pub field_desc: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "field_type")]
    pub field_type: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "old_value_integer")]
    pub old_value_integer: Option<i32>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "old_value_float")]
    pub old_value_float: Option<f64>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "old_value_text")]
    pub old_value_text: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "old_value_datetime")]
    pub old_value_datetime: Option<DateTime<Utc>>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "new_value_integer")]
    pub new_value_integer: Option<i32>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "new_value_float")]
    pub new_value_float: Option<f64>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "new_value_text")]
    pub new_value_text: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "new_value_datetime")]
    pub new_value_datetime: Option<DateTime<Utc>>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "currency_id")]
    pub currency_id: Option<Uuid>,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a MailTrackingValue
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchMailTrackingValueDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "mail_message_id")]
    pub mail_message_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub field: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "field_desc")]
    pub field_desc: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "field_type")]
    pub field_type: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "old_value_integer")]
    pub old_value_integer: Option<i32>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "old_value_float")]
    pub old_value_float: Option<f64>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "old_value_text")]
    pub old_value_text: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "old_value_datetime")]
    pub old_value_datetime: Option<DateTime<Utc>>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "new_value_integer")]
    pub new_value_integer: Option<i32>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "new_value_float")]
    pub new_value_float: Option<f64>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "new_value_text")]
    pub new_value_text: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "new_value_datetime")]
    pub new_value_datetime: Option<DateTime<Utc>>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "currency_id")]
    pub currency_id: Option<Uuid>,
}

impl PatchMailTrackingValueDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.mail_message_id.is_some() || self.field.is_some() || self.field_desc.is_some() || self.field_type.is_some() || self.old_value_integer.is_some() || self.old_value_float.is_some() || self.old_value_text.is_some() || self.old_value_datetime.is_some() || self.new_value_integer.is_some() || self.new_value_float.is_some() || self.new_value_text.is_some() || self.new_value_datetime.is_some() || self.currency_id.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for MailTrackingValue entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct MailTrackingValueResponseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub mail_message_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub field: String,
    pub field_desc: Option<String>,
    pub field_type: Option<String>,
    pub old_value_integer: Option<i32>,
    pub old_value_float: Option<f64>,
    pub old_value_text: Option<String>,
    pub old_value_datetime: Option<DateTime<Utc>>,
    pub new_value_integer: Option<i32>,
    pub new_value_float: Option<f64>,
    pub new_value_text: Option<String>,
    pub new_value_datetime: Option<DateTime<Utc>>,
    pub currency_id: Option<Uuid>,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for MailTrackingValue entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct MailTrackingValueListResponseDto {
    /// List of items
    pub items: Vec<MailTrackingValueResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl MailTrackingValueListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<MailTrackingValueResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct MailTrackingValueSummaryDto {
    pub id: Uuid,
    pub mail_message_id: Uuid,
    pub field: String,
    pub field_desc: Option<String>,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<MailTrackingValue> for MailTrackingValueResponseDto {
    fn from(entity: MailTrackingValue) -> Self {
        Self {
            id: entity.id,
            mail_message_id: entity.mail_message_id,
            field: entity.field,
            field_desc: entity.field_desc,
            field_type: entity.field_type,
            old_value_integer: entity.old_value_integer,
            old_value_float: entity.old_value_float,
            old_value_text: entity.old_value_text,
            old_value_datetime: entity.old_value_datetime,
            new_value_integer: entity.new_value_integer,
            new_value_float: entity.new_value_float,
            new_value_text: entity.new_value_text,
            new_value_datetime: entity.new_value_datetime,
            currency_id: entity.currency_id,
            metadata: entity.metadata,
        }
    }
}

impl From<MailTrackingValue> for MailTrackingValueSummaryDto {
    fn from(entity: MailTrackingValue) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            mail_message_id: entity.mail_message_id,
            field: entity.field,
            field_desc: entity.field_desc,
            created_at,
        }
    }
}

impl From<CreateMailTrackingValueDto> for MailTrackingValue {
    fn from(dto: CreateMailTrackingValueDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            mail_message_id: dto.mail_message_id,
            field: dto.field,
            field_desc: dto.field_desc,
            field_type: dto.field_type,
            old_value_integer: dto.old_value_integer,
            old_value_float: dto.old_value_float,
            old_value_text: dto.old_value_text,
            old_value_datetime: dto.old_value_datetime,
            new_value_integer: dto.new_value_integer,
            new_value_float: dto.new_value_float,
            new_value_text: dto.new_value_text,
            new_value_datetime: dto.new_value_datetime,
            currency_id: dto.currency_id,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&MailTrackingValue> for MailTrackingValueResponseDto {
    fn from(entity: &MailTrackingValue) -> Self {
        Self {
            id: entity.id.clone(),
            mail_message_id: entity.mail_message_id.clone(),
            field: entity.field.clone(),
            field_desc: entity.field_desc.clone(),
            field_type: entity.field_type.clone(),
            old_value_integer: entity.old_value_integer.clone(),
            old_value_float: entity.old_value_float.clone(),
            old_value_text: entity.old_value_text.clone(),
            old_value_datetime: entity.old_value_datetime.clone(),
            new_value_integer: entity.new_value_integer.clone(),
            new_value_float: entity.new_value_float.clone(),
            new_value_text: entity.new_value_text.clone(),
            new_value_datetime: entity.new_value_datetime.clone(),
            currency_id: entity.currency_id.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreateMailTrackingValueDto> for MailTrackingValue {
    fn from_create_dto(dto: CreateMailTrackingValueDto) -> backbone_core::ServiceResult<Self> {
        Ok(MailTrackingValue::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdateMailTrackingValueDto> for MailTrackingValue {
    fn apply_update(mut self, dto: UpdateMailTrackingValueDto) -> backbone_core::ServiceResult<Self> {
        self.mail_message_id = dto.mail_message_id;
        self.field = dto.field;
        self.field_desc = dto.field_desc;
        self.field_type = dto.field_type;
        self.old_value_integer = dto.old_value_integer;
        self.old_value_float = dto.old_value_float;
        self.old_value_text = dto.old_value_text;
        self.old_value_datetime = dto.old_value_datetime;
        self.new_value_integer = dto.new_value_integer;
        self.new_value_float = dto.new_value_float;
        self.new_value_text = dto.new_value_text;
        self.new_value_datetime = dto.new_value_datetime;
        self.currency_id = dto.currency_id;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to MailTrackingValue here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs
