//! MailNotification DTOs (Data Transfer Objects)
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc};

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::MailNotification;
use crate::domain::entity::AuditMetadata;
use crate::domain::entity::MailNotificationStatus;
use crate::domain::entity::MailNotificationType;
use crate::domain::entity::NotificationFailureType;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new MailNotification
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreateMailNotificationDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "mail_message_id")]
    pub mail_message_id: Uuid,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "res_partner_id")]
    pub res_partner_id: Option<Uuid>,
    #[serde(alias = "notification_type")]
    pub notification_type: MailNotificationType,
    #[serde(alias = "notification_status")]
    pub notification_status: MailNotificationStatus,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "failure_type")]
    pub failure_type: Option<NotificationFailureType>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "failure_reason")]
    pub failure_reason: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "mail_mail_id_int")]
    pub mail_mail_id_int: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(alias = "is_read")]
    pub is_read: bool,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a MailNotification
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdateMailNotificationDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "mail_message_id")]
    pub mail_message_id: Uuid,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "res_partner_id")]
    pub res_partner_id: Option<Uuid>,
    #[serde(alias = "notification_type")]
    pub notification_type: MailNotificationType,
    #[serde(alias = "notification_status")]
    pub notification_status: MailNotificationStatus,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "failure_type")]
    pub failure_type: Option<NotificationFailureType>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "failure_reason")]
    pub failure_reason: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "mail_mail_id_int")]
    pub mail_mail_id_int: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(alias = "is_read")]
    pub is_read: bool,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a MailNotification
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchMailNotificationDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "mail_message_id")]
    pub mail_message_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "res_partner_id")]
    pub res_partner_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "notification_type")]
    pub notification_type: Option<MailNotificationType>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "notification_status")]
    pub notification_status: Option<MailNotificationStatus>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "failure_type")]
    pub failure_type: Option<NotificationFailureType>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "failure_reason")]
    pub failure_reason: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "mail_mail_id_int")]
    pub mail_mail_id_int: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "is_read")]
    pub is_read: Option<bool>,
}

impl PatchMailNotificationDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.mail_message_id.is_some() || self.res_partner_id.is_some() || self.notification_type.is_some() || self.notification_status.is_some() || self.failure_type.is_some() || self.failure_reason.is_some() || self.mail_mail_id_int.is_some() || self.is_read.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for MailNotification entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct MailNotificationResponseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub mail_message_id: Uuid,
    pub res_partner_id: Option<Uuid>,
    pub notification_type: MailNotificationType,
    pub notification_status: MailNotificationStatus,
    pub failure_type: Option<NotificationFailureType>,
    pub failure_reason: Option<String>,
    pub mail_mail_id_int: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub is_read: bool,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for MailNotification entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct MailNotificationListResponseDto {
    /// List of items
    pub items: Vec<MailNotificationResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl MailNotificationListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<MailNotificationResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct MailNotificationSummaryDto {
    pub id: Uuid,
    pub mail_message_id: Uuid,
    pub res_partner_id: Option<Uuid>,
    pub notification_type: MailNotificationType,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<MailNotification> for MailNotificationResponseDto {
    fn from(entity: MailNotification) -> Self {
        Self {
            id: entity.id,
            mail_message_id: entity.mail_message_id,
            res_partner_id: entity.res_partner_id,
            notification_type: entity.notification_type,
            notification_status: entity.notification_status,
            failure_type: entity.failure_type,
            failure_reason: entity.failure_reason,
            mail_mail_id_int: entity.mail_mail_id_int,
            is_read: entity.is_read,
            metadata: entity.metadata,
        }
    }
}

impl From<MailNotification> for MailNotificationSummaryDto {
    fn from(entity: MailNotification) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            mail_message_id: entity.mail_message_id,
            res_partner_id: entity.res_partner_id,
            notification_type: entity.notification_type,
            created_at,
        }
    }
}

impl From<CreateMailNotificationDto> for MailNotification {
    fn from(dto: CreateMailNotificationDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            mail_message_id: dto.mail_message_id,
            res_partner_id: dto.res_partner_id,
            notification_type: dto.notification_type,
            notification_status: dto.notification_status,
            failure_type: dto.failure_type,
            failure_reason: dto.failure_reason,
            mail_mail_id_int: dto.mail_mail_id_int,
            is_read: dto.is_read,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&MailNotification> for MailNotificationResponseDto {
    fn from(entity: &MailNotification) -> Self {
        Self {
            id: entity.id.clone(),
            mail_message_id: entity.mail_message_id.clone(),
            res_partner_id: entity.res_partner_id.clone(),
            notification_type: entity.notification_type.clone(),
            notification_status: entity.notification_status.clone(),
            failure_type: entity.failure_type.clone(),
            failure_reason: entity.failure_reason.clone(),
            mail_mail_id_int: entity.mail_mail_id_int.clone(),
            is_read: entity.is_read.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreateMailNotificationDto> for MailNotification {
    fn from_create_dto(dto: CreateMailNotificationDto) -> backbone_core::ServiceResult<Self> {
        Ok(MailNotification::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdateMailNotificationDto> for MailNotification {
    fn apply_update(mut self, dto: UpdateMailNotificationDto) -> backbone_core::ServiceResult<Self> {
        self.mail_message_id = dto.mail_message_id;
        self.res_partner_id = dto.res_partner_id;
        self.notification_type = dto.notification_type;
        self.notification_status = dto.notification_status;
        self.failure_type = dto.failure_type;
        self.failure_reason = dto.failure_reason;
        self.mail_mail_id_int = dto.mail_mail_id_int;
        self.is_read = dto.is_read;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to MailNotification here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs

