//! MailGuest DTOs (Data Transfer Objects)
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc};

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::MailGuest;
use crate::domain::entity::AuditMetadata;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new MailGuest
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreateMailGuestDto {
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub name: String,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "country_id")]
    pub country_id: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "last_connection_dt")]
    pub last_connection_dt: Option<DateTime<Utc>>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub active: bool,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a MailGuest
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdateMailGuestDto {
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub name: String,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "country_id")]
    pub country_id: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "last_connection_dt")]
    pub last_connection_dt: Option<DateTime<Utc>>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub active: bool,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a MailGuest
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchMailGuestDto {
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "country_id")]
    pub country_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "last_connection_dt")]
    pub last_connection_dt: Option<DateTime<Utc>>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub active: Option<bool>,
}

impl PatchMailGuestDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.name.is_some() || self.country_id.is_some() || self.last_connection_dt.is_some() || self.active.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for MailGuest entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct MailGuestResponseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub name: String,
    pub country_id: Option<Uuid>,
    pub last_connection_dt: Option<DateTime<Utc>>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub active: bool,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for MailGuest entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct MailGuestListResponseDto {
    /// List of items
    pub items: Vec<MailGuestResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl MailGuestListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<MailGuestResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct MailGuestSummaryDto {
    pub id: Uuid,
    pub name: String,
    pub country_id: Option<Uuid>,
    pub last_connection_dt: Option<DateTime<Utc>>,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<MailGuest> for MailGuestResponseDto {
    fn from(entity: MailGuest) -> Self {
        Self {
            id: entity.id,
            name: entity.name,
            country_id: entity.country_id,
            last_connection_dt: entity.last_connection_dt,
            active: entity.active,
            metadata: entity.metadata,
        }
    }
}

impl From<MailGuest> for MailGuestSummaryDto {
    fn from(entity: MailGuest) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            name: entity.name,
            country_id: entity.country_id,
            last_connection_dt: entity.last_connection_dt,
            created_at,
        }
    }
}

impl From<CreateMailGuestDto> for MailGuest {
    fn from(dto: CreateMailGuestDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            name: dto.name,
            country_id: dto.country_id,
            last_connection_dt: dto.last_connection_dt,
            active: dto.active,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&MailGuest> for MailGuestResponseDto {
    fn from(entity: &MailGuest) -> Self {
        Self {
            id: entity.id.clone(),
            name: entity.name.clone(),
            country_id: entity.country_id.clone(),
            last_connection_dt: entity.last_connection_dt.clone(),
            active: entity.active.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreateMailGuestDto> for MailGuest {
    fn from_create_dto(dto: CreateMailGuestDto) -> backbone_core::ServiceResult<Self> {
        Ok(MailGuest::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdateMailGuestDto> for MailGuest {
    fn apply_update(mut self, dto: UpdateMailGuestDto) -> backbone_core::ServiceResult<Self> {
        self.name = dto.name;
        self.country_id = dto.country_id;
        self.last_connection_dt = dto.last_connection_dt;
        self.active = dto.active;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to MailGuest here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs
