//! Sms DTOs (Data Transfer Objects)
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc};

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::Sms;
use crate::domain::entity::AuditMetadata;
use crate::domain::entity::SmsFailureType;
use crate::domain::entity::SmsState;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new Sms
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreateSmsDto {
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub uuid: String,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub number: String,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub body: String,
    pub state: SmsState,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "failure_type")]
    pub failure_type: Option<SmsFailureType>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "error_message")]
    pub error_message: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "mail_message_id")]
    pub mail_message_id: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "iap_status_code")]
    pub iap_status_code: Option<i32>,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a Sms
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdateSmsDto {
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub uuid: String,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub number: String,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub body: String,
    pub state: SmsState,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "failure_type")]
    pub failure_type: Option<SmsFailureType>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "error_message")]
    pub error_message: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "mail_message_id")]
    pub mail_message_id: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "iap_status_code")]
    pub iap_status_code: Option<i32>,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a Sms
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchSmsDto {
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub uuid: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub number: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub body: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub state: Option<SmsState>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "failure_type")]
    pub failure_type: Option<SmsFailureType>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "error_message")]
    pub error_message: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "mail_message_id")]
    pub mail_message_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "iap_status_code")]
    pub iap_status_code: Option<i32>,
}

impl PatchSmsDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.uuid.is_some() || self.number.is_some() || self.body.is_some() || self.state.is_some() || self.failure_type.is_some() || self.error_message.is_some() || self.mail_message_id.is_some() || self.iap_status_code.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for Sms entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct SmsResponseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub uuid: String,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub number: String,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub body: String,
    pub state: SmsState,
    pub failure_type: Option<SmsFailureType>,
    pub error_message: Option<String>,
    pub mail_message_id: Option<Uuid>,
    pub iap_status_code: Option<i32>,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for Sms entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct SmsListResponseDto {
    /// List of items
    pub items: Vec<SmsResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl SmsListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<SmsResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct SmsSummaryDto {
    pub id: Uuid,
    pub uuid: String,
    pub number: String,
    pub body: String,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<Sms> for SmsResponseDto {
    fn from(entity: Sms) -> Self {
        Self {
            id: entity.id,
            uuid: entity.uuid,
            number: entity.number,
            body: entity.body,
            state: entity.state,
            failure_type: entity.failure_type,
            error_message: entity.error_message,
            mail_message_id: entity.mail_message_id,
            iap_status_code: entity.iap_status_code,
            metadata: entity.metadata,
        }
    }
}

impl From<Sms> for SmsSummaryDto {
    fn from(entity: Sms) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            uuid: entity.uuid,
            number: entity.number,
            body: entity.body,
            created_at,
        }
    }
}

impl From<CreateSmsDto> for Sms {
    fn from(dto: CreateSmsDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            uuid: dto.uuid,
            number: dto.number,
            body: dto.body,
            state: dto.state,
            failure_type: dto.failure_type,
            error_message: dto.error_message,
            mail_message_id: dto.mail_message_id,
            iap_status_code: dto.iap_status_code,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&Sms> for SmsResponseDto {
    fn from(entity: &Sms) -> Self {
        Self {
            id: entity.id.clone(),
            uuid: entity.uuid.clone(),
            number: entity.number.clone(),
            body: entity.body.clone(),
            state: entity.state.clone(),
            failure_type: entity.failure_type.clone(),
            error_message: entity.error_message.clone(),
            mail_message_id: entity.mail_message_id.clone(),
            iap_status_code: entity.iap_status_code.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreateSmsDto> for Sms {
    fn from_create_dto(dto: CreateSmsDto) -> backbone_core::ServiceResult<Self> {
        Ok(Sms::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdateSmsDto> for Sms {
    fn apply_update(mut self, dto: UpdateSmsDto) -> backbone_core::ServiceResult<Self> {
        self.uuid = dto.uuid;
        self.number = dto.number;
        self.body = dto.body;
        self.state = dto.state;
        self.failure_type = dto.failure_type;
        self.error_message = dto.error_message;
        self.mail_message_id = dto.mail_message_id;
        self.iap_status_code = dto.iap_status_code;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to Sms here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs

