//! SmsTemplate DTOs (Data Transfer Objects)
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc};

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::SmsTemplate;
use crate::domain::entity::AuditMetadata;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new SmsTemplate
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreateSmsTemplateDto {
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub name: String,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub body: String,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "model_id")]
    pub model_id: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub lang: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub condition: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub active: bool,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a SmsTemplate
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdateSmsTemplateDto {
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub name: String,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub body: String,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "model_id")]
    pub model_id: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub lang: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub condition: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub active: bool,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a SmsTemplate
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchSmsTemplateDto {
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub body: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "model_id")]
    pub model_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub lang: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub condition: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub active: Option<bool>,
}

impl PatchSmsTemplateDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.name.is_some() || self.body.is_some() || self.model_id.is_some() || self.lang.is_some() || self.condition.is_some() || self.active.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for SmsTemplate entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct SmsTemplateResponseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub name: String,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub body: String,
    pub model_id: Option<Uuid>,
    pub lang: Option<String>,
    pub condition: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub active: bool,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for SmsTemplate entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct SmsTemplateListResponseDto {
    /// List of items
    pub items: Vec<SmsTemplateResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl SmsTemplateListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<SmsTemplateResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct SmsTemplateSummaryDto {
    pub id: Uuid,
    pub name: String,
    pub body: String,
    pub model_id: Option<Uuid>,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<SmsTemplate> for SmsTemplateResponseDto {
    fn from(entity: SmsTemplate) -> Self {
        Self {
            id: entity.id,
            name: entity.name,
            body: entity.body,
            model_id: entity.model_id,
            lang: entity.lang,
            condition: entity.condition,
            active: entity.active,
            metadata: entity.metadata,
        }
    }
}

impl From<SmsTemplate> for SmsTemplateSummaryDto {
    fn from(entity: SmsTemplate) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            name: entity.name,
            body: entity.body,
            model_id: entity.model_id,
            created_at,
        }
    }
}

impl From<CreateSmsTemplateDto> for SmsTemplate {
    fn from(dto: CreateSmsTemplateDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            name: dto.name,
            body: dto.body,
            model_id: dto.model_id,
            lang: dto.lang,
            condition: dto.condition,
            active: dto.active,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&SmsTemplate> for SmsTemplateResponseDto {
    fn from(entity: &SmsTemplate) -> Self {
        Self {
            id: entity.id.clone(),
            name: entity.name.clone(),
            body: entity.body.clone(),
            model_id: entity.model_id.clone(),
            lang: entity.lang.clone(),
            condition: entity.condition.clone(),
            active: entity.active.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreateSmsTemplateDto> for SmsTemplate {
    fn from_create_dto(dto: CreateSmsTemplateDto) -> backbone_core::ServiceResult<Self> {
        Ok(SmsTemplate::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdateSmsTemplateDto> for SmsTemplate {
    fn apply_update(mut self, dto: UpdateSmsTemplateDto) -> backbone_core::ServiceResult<Self> {
        self.name = dto.name;
        self.body = dto.body;
        self.model_id = dto.model_id;
        self.lang = dto.lang;
        self.condition = dto.condition;
        self.active = dto.active;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to SmsTemplate here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs

