//! Domain policy for MailAliasDomain aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! `DomainPolicy` enforces pure business invariants (state-based rules).
//! Identity-based rules live in `backbone_auth::ResourcePolicy`.

use async_trait::async_trait;
use backbone_core::{DomainPolicy, PolicyDecision};
use crate::domain::entity::MailAliasDomain;

/// Domain policy for MailAliasDomain — enforces business invariants.
pub struct MailAliasDomainDomainPolicy;

#[async_trait]
impl DomainPolicy<MailAliasDomain> for MailAliasDomainDomainPolicy {
    // <<< CUSTOM
    // Add entity-specific invariant checks here.
    // Example:
    // async fn can_delete(&self, entity: &MailAliasDomain) -> PolicyDecision {
    //     if entity.is_locked {
    //         Err("locked mail_alias_domain cannot be deleted".into())
    //     } else { Ok(true) }
    // }
    // END CUSTOM
}
