//! Domain policy for MailFollowers aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! `DomainPolicy` enforces pure business invariants (state-based rules).
//! Identity-based rules live in `backbone_auth::ResourcePolicy`.

use async_trait::async_trait;
use backbone_core::{DomainPolicy, PolicyDecision};
use crate::domain::entity::MailFollowers;

/// Domain policy for MailFollowers — enforces business invariants.
pub struct MailFollowersDomainPolicy;

#[async_trait]
impl DomainPolicy<MailFollowers> for MailFollowersDomainPolicy {
    // <<< CUSTOM
    // Add entity-specific invariant checks here.
    // Example:
    // async fn can_delete(&self, entity: &MailFollowers) -> PolicyDecision {
    //     if entity.is_locked {
    //         Err("locked mail_followers cannot be deleted".into())
    //     } else { Ok(true) }
    // }
    // END CUSTOM
}
