//! Domain policy for SmsTracker aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! `DomainPolicy` enforces pure business invariants (state-based rules).
//! Identity-based rules live in `backbone_auth::ResourcePolicy`.

use async_trait::async_trait;
use backbone_core::{DomainPolicy, PolicyDecision};
use crate::domain::entity::SmsTracker;

/// Domain policy for SmsTracker — enforces business invariants.
pub struct SmsTrackerDomainPolicy;

#[async_trait]
impl DomainPolicy<SmsTracker> for SmsTrackerDomainPolicy {
    // <<< CUSTOM
    // Add entity-specific invariant checks here.
    // Example:
    // async fn can_delete(&self, entity: &SmsTracker) -> PolicyDecision {
    //     if entity.is_locked {
    //         Err("locked sms_tracker cannot be deleted".into())
    //     } else { Ok(true) }
    // }
    // END CUSTOM
}
