//! Application service for MailMessageSchedule entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `mail_message_schedule_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreateMailMessageScheduleDto, UpdateMailMessageScheduleDto};
use crate::domain::entity::MailMessageSchedule;
use crate::infrastructure::persistence::MailMessageScheduleRepository;

/// Application service for MailMessageSchedule entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `mail_message_schedule_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct MailMessageScheduleServiceCustom {
///     inner: Arc<MailMessageScheduleService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type MailMessageScheduleService = GenericCrudService<
    MailMessageSchedule,
    CreateMailMessageScheduleDto,
    UpdateMailMessageScheduleDto,
    MailMessageScheduleRepository,
>;

// <<< CUSTOM
// END CUSTOM
