//! Application service for MailAliasDomain entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `mail_alias_domain_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreateMailAliasDomainDto, UpdateMailAliasDomainDto};
use crate::domain::entity::MailAliasDomain;
use crate::infrastructure::persistence::MailAliasDomainRepository;

/// Application service for MailAliasDomain entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `mail_alias_domain_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct MailAliasDomainServiceCustom {
///     inner: Arc<MailAliasDomainService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type MailAliasDomainService = GenericCrudService<
    MailAliasDomain,
    CreateMailAliasDomainDto,
    UpdateMailAliasDomainDto,
    MailAliasDomainRepository,
>;

// <<< CUSTOM
// END CUSTOM
