//! Application service for MailMessageStar entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `mail_message_star_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreateMailMessageStarDto, UpdateMailMessageStarDto};
use crate::domain::entity::MailMessageStar;
use crate::infrastructure::persistence::MailMessageStarRepository;

/// Application service for MailMessageStar entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `mail_message_star_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct MailMessageStarServiceCustom {
///     inner: Arc<MailMessageStarService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type MailMessageStarService = GenericCrudService<
    MailMessageStar,
    CreateMailMessageStarDto,
    UpdateMailMessageStarDto,
    MailMessageStarRepository,
>;

// <<< CUSTOM
// END CUSTOM
