//! Application service for MailGatewayAllowed entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `mail_gateway_allowed_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreateMailGatewayAllowedDto, UpdateMailGatewayAllowedDto};
use crate::domain::entity::MailGatewayAllowed;
use crate::infrastructure::persistence::MailGatewayAllowedRepository;

/// Application service for MailGatewayAllowed entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `mail_gateway_allowed_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct MailGatewayAllowedServiceCustom {
///     inner: Arc<MailGatewayAllowedService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type MailGatewayAllowedService = GenericCrudService<
    MailGatewayAllowed,
    CreateMailGatewayAllowedDto,
    UpdateMailGatewayAllowedDto,
    MailGatewayAllowedRepository,
>;

// <<< CUSTOM
// END CUSTOM
