//! Application service for MailScheduledMessage entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `mail_scheduled_message_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreateMailScheduledMessageDto, UpdateMailScheduledMessageDto};
use crate::domain::entity::MailScheduledMessage;
use crate::infrastructure::persistence::MailScheduledMessageRepository;

/// Application service for MailScheduledMessage entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `mail_scheduled_message_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct MailScheduledMessageServiceCustom {
///     inner: Arc<MailScheduledMessageService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type MailScheduledMessageService = GenericCrudService<
    MailScheduledMessage,
    CreateMailScheduledMessageDto,
    UpdateMailScheduledMessageDto,
    MailScheduledMessageRepository,
>;

// <<< CUSTOM
// END CUSTOM
