//! Application services
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each entity service is a type alias over `GenericCrudService`.

pub mod error;
pub use error::{ServiceError, ServiceResult};

pub mod mail_activity_service;
pub mod mail_activity_type_service;
pub mod mail_activity_plan_service;
pub mod mail_activity_plan_template_service;
pub mod mail_alias_domain_service;
pub mod mail_alias_service;
pub mod mail_attachment_service;
pub mod mail_message_attachment_service;
pub mod mail_message_star_service;
pub mod mail_message_service;
pub mod mail_service;
pub mod mail_notification_service;
pub mod mail_message_subtype_service;
pub mod mail_message_reaction_service;
pub mod mail_followers_service;
pub mod mail_presence_service;
pub mod mail_blacklist_service;
pub mod mail_tracking_value_service;
pub mod discuss_channel_service;
pub mod discuss_channel_member_service;
pub mod mail_guest_service;
pub mod mail_message_schedule_service;
pub mod mail_scheduled_message_service;
pub mod sms_service;
pub mod sms_template_service;
pub mod sms_tracker_service;

// <<< CUSTOM
// END CUSTOM

pub use mail_activity_service::MailActivityService;
pub use mail_activity_type_service::MailActivityTypeService;
pub use mail_activity_plan_service::MailActivityPlanService;
pub use mail_activity_plan_template_service::MailActivityPlanTemplateService;
pub use mail_alias_domain_service::MailAliasDomainService;
pub use mail_alias_service::MailAliasService;
pub use mail_attachment_service::MailAttachmentService;
pub use mail_message_attachment_service::MailMessageAttachmentService;
pub use mail_message_star_service::MailMessageStarService;
pub use mail_message_service::MailMessageService;
pub use mail_service::MailService;
pub use mail_notification_service::MailNotificationService;
pub use mail_message_subtype_service::MailMessageSubtypeService;
pub use mail_message_reaction_service::MailMessageReactionService;
pub use mail_followers_service::MailFollowersService;
pub use mail_presence_service::MailPresenceService;
pub use mail_blacklist_service::MailBlacklistService;
pub use mail_tracking_value_service::MailTrackingValueService;
pub use discuss_channel_service::DiscussChannelService;
pub use discuss_channel_member_service::DiscussChannelMemberService;
pub use mail_guest_service::MailGuestService;
pub use mail_message_schedule_service::MailMessageScheduleService;
pub use mail_scheduled_message_service::MailScheduledMessageService;
pub use sms_service::SmsService;
pub use sms_template_service::SmsTemplateService;
pub use sms_tracker_service::SmsTrackerService;
// <<< CUSTOM
// Hand-authored messaging write services (increment 1; user-owned files declared in
// metaphor.codegen.yaml — regen never touches them).
pub mod sms_ports;
pub mod message_write_service;
pub mod follower_write_service;
pub mod activity_write_service;
pub mod sms_write_service;
pub mod mail_queue_write_service;
pub mod alias_write_service;

pub use alias_write_service::{AliasError, AliasWriteService};
pub use follower_write_service::{FollowerError, FollowerWriteService};
pub use message_write_service::{
    MailError, MessagePostCommand, MessageWriteService, NotificationChannel, PostRecipient,
    PostedMessage,
};
pub use activity_write_service::{ActivityError, ActivityWriteService, ScheduleActivity};
pub use mail_queue_write_service::{MailDrainOutcome, MailQueueError, MailQueueWriteService};
pub use sms_ports::{
    NoopSmsApi, SmsApiPort, SmsSendFailure, SmsSendOutcome, SmsSendRequest,
};
pub use sms_write_service::{DrainOutcome, SmsError, SmsWriteService};
pub use crate::infrastructure::persistence::follower_repository::ExistingPolicy;
pub use crate::infrastructure::persistence::follower_repository::SubscribeOutcome;

// Increment-2 surface (user-owned): channel/member ops, typing, reactions,
// presence, guests, schedules, webhook, GC, attachments, query services,
// and the chatter ACL seam + host facade.
pub mod chatter_acl;
pub mod channel_write_service;
pub mod channel_member_write_service;
pub mod channel_query_service;
pub mod typing_service;
pub mod reaction_write_service;
pub mod message_edit_service;
pub mod guest_write_service;
pub mod presence_write_service;
pub mod schedule_write_service;
pub mod sms_status_webhook_service;
pub mod gc_service;
pub mod attachment_write_service;
pub mod message_query_service;
pub mod recipient_query_service;
pub mod thread_chatter_service;

pub use chatter_acl::{
    DenyHostDocs, MessagingIdentity, StaticThreadAccess, ThreadAclSlot, ThreadAccessResolver,
};
pub use channel_write_service::{ChannelError, ChannelWriteService};
pub use channel_member_write_service::{ChannelMemberWriteService, MemberError};
pub use channel_query_service::{ChannelQueryError, ChannelQueryService, ChannelSearchHit};
pub use typing_service::{TypingError, TypingService};
pub use reaction_write_service::{ReactionError, ReactionWriteService};
pub use message_edit_service::{MessageEditError, MessageEditService};
pub use guest_write_service::{GuestError, GuestWriteService};
pub use presence_write_service::{PresenceError, PresenceWriteService};
pub use schedule_write_service::{ScheduleError, ScheduleWriteService};
pub use sms_status_webhook_service::{
    SmsStatusWebhookService, WebhookError, WebhookOutcome, WEBHOOK_SCHEME,
};
pub use gc_service::{GcError, GcService};
pub use attachment_write_service::{AttachmentError, AttachmentWriteService};
pub use message_query_service::{MessageQueryError, MessageQueryService};
pub use recipient_query_service::{
    RecipientQueryError, RecipientQueryService, SuggestedRecipient,
};
pub use thread_chatter_service::{ChatterError, ThreadChatterService};
// END CUSTOM