//! Application service for SmsTemplate entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `sms_template_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreateSmsTemplateDto, UpdateSmsTemplateDto};
use crate::domain::entity::SmsTemplate;
use crate::infrastructure::persistence::SmsTemplateRepository;

/// Application service for SmsTemplate entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `sms_template_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct SmsTemplateServiceCustom {
///     inner: Arc<SmsTemplateService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type SmsTemplateService = GenericCrudService<
    SmsTemplate,
    CreateSmsTemplateDto,
    UpdateSmsTemplateDto,
    SmsTemplateRepository,
>;

// <<< CUSTOM
// END CUSTOM
