-- FetchmailServer Seed Data
-- Generated by metaphor-schema
--
-- This file contains initial seed data for the messaging.fetchmail_servers table.
-- Customize this file to add your initial data.

-- INSERT INTO messaging.fetchmail_servers (
--     id,
--     name,
--     active,
--     state,
--     default_thread_model,
--     priority,
--     token_hash,
--     last_fetch_at,
--     error_at,
--     error_message,
--     metadata
-- ) VALUES
-- (
--     -- Add values here
-- );

-- Example: Insert reference data
-- Uncomment and modify the following:

-- INSERT INTO messaging.fetchmail_servers (id, code, name, is_active, created_at, updated_at) VALUES
--     (gen_random_uuid(), 'SAMPLE1', 'Sample 1', true, NOW(), NOW()),
--     (gen_random_uuid(), 'SAMPLE2', 'Sample 2', true, NOW(), NOW());

-- <<< CUSTOM SEED DATA >>>
-- Add your custom seed data below

