-- MailTrackingValue Seed Data
-- Generated by metaphor-schema
--
-- This file contains initial seed data for the messaging.mail_tracking_values table.
-- Customize this file to add your initial data.

-- INSERT INTO messaging.mail_tracking_values (
--     id,
--     mail_message_id,
--     field,
--     field_desc,
--     field_type,
--     old_value_integer,
--     old_value_float,
--     old_value_text,
--     old_value_datetime,
--     new_value_integer,
--     new_value_float,
--     new_value_text,
--     new_value_datetime,
--     currency_id,
--     metadata
-- ) VALUES
-- (
--     -- Add values here
-- );

-- Example: Insert test data
-- Uncomment and modify the following for development/testing:

-- INSERT INTO messaging.mail_tracking_values (id, created_at, updated_at) VALUES
--     (gen_random_uuid(), NOW(), NOW());

-- <<< CUSTOM SEED DATA >>>
-- Add your custom seed data below

