-- MailNotification Seed Data
-- Generated by metaphor-schema
--
-- This file contains initial seed data for the messaging.mail_notifications table.
-- Customize this file to add your initial data.

-- INSERT INTO messaging.mail_notifications (
--     id,
--     mail_message_id,
--     res_partner_id,
--     notification_type,
--     notification_status,
--     failure_type,
--     failure_reason,
--     mail_mail_id_int,
--     is_read,
--     metadata
-- ) VALUES
-- (
--     -- Add values here
-- );

-- Example: Insert test data
-- Uncomment and modify the following for development/testing:

-- INSERT INTO messaging.mail_notifications (id, created_at, updated_at) VALUES
--     (gen_random_uuid(), NOW(), NOW());

-- <<< CUSTOM SEED DATA >>>
-- Add your custom seed data below

