-- MailMessageSubtype Seed Data
-- Generated by metaphor-schema
--
-- This file contains initial seed data for the messaging.mail_message_subtypes table.
-- Customize this file to add your initial data.

-- INSERT INTO messaging.mail_message_subtypes (
--     id,
--     name,
--     description,
--     internal,
--     parent_id,
--     relation_field,
--     res_model,
--     default,
--     hidden,
--     tracked,
--     metadata
-- ) VALUES
-- (
--     -- Add values here
-- );

-- Example: Insert reference data
-- Uncomment and modify the following:

-- INSERT INTO messaging.mail_message_subtypes (id, code, name, is_active, created_at, updated_at) VALUES
--     (gen_random_uuid(), 'SAMPLE1', 'Sample 1', true, NOW(), NOW()),
--     (gen_random_uuid(), 'SAMPLE2', 'Sample 2', true, NOW(), NOW());

-- <<< CUSTOM SEED DATA >>>
-- Add your custom seed data below

