-- PhoneBlacklist Seed Data
-- Generated by metaphor-schema
--
-- This file contains initial seed data for the messaging.phone_blacklists table.
-- Customize this file to add your initial data.

-- INSERT INTO messaging.phone_blacklists (
--     id,
--     number,
--     active,
--     metadata
-- ) VALUES
-- (
--     -- Add values here
-- );

-- Example: Insert test data
-- Uncomment and modify the following for development/testing:

-- INSERT INTO messaging.phone_blacklists (id, created_at, updated_at) VALUES
--     (gen_random_uuid(), NOW(), NOW());

-- <<< CUSTOM SEED DATA >>>
-- Add your custom seed data below

