-- SmsTracker Seed Data
-- Generated by metaphor-schema
--
-- This file contains initial seed data for the messaging.sms_trackers table.
-- Customize this file to add your initial data.

-- INSERT INTO messaging.sms_trackers (
--     id,
--     sms_uuid,
--     message_id,
--     notification_id,
--     state,
--     failure_type,
--     failure_reason,
--     recipient,
--     metadata
-- ) VALUES
-- (
--     -- Add values here
-- );

-- Example: Insert test data
-- Uncomment and modify the following for development/testing:

-- INSERT INTO messaging.sms_trackers (id, created_at, updated_at) VALUES
--     (gen_random_uuid(), NOW(), NOW());

-- <<< CUSTOM SEED DATA >>>
-- Add your custom seed data below

