-- Migration: Create mail_servers table
-- Generated by metaphor-schema

-- Create smtp_authentication enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'smtp_authentication') THEN
        CREATE TYPE smtp_authentication AS ENUM ('login', 'certificate');
    END IF;
END
$$;

-- Create smtp_encryption enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'smtp_encryption') THEN
        CREATE TYPE smtp_encryption AS ENUM ('none', 'starttls', 'ssl');
    END IF;
END
$$;

CREATE SCHEMA IF NOT EXISTS messaging;

CREATE TABLE IF NOT EXISTS messaging.mail_servers (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    name TEXT NOT NULL,
    from_filter TEXT,
    smtp_host TEXT NOT NULL,
    smtp_port INTEGER NOT NULL DEFAULT 25,
    smtp_authentication smtp_authentication NOT NULL DEFAULT 'login',
    smtp_user TEXT,
    smtp_pass_ref TEXT,
    smtp_encryption smtp_encryption NOT NULL DEFAULT 'none',
    smtp_debug BOOLEAN NOT NULL DEFAULT FALSE,
    sequence INTEGER NOT NULL DEFAULT 10,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS mail_server_sequence_idx ON messaging.mail_servers (sequence);

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_mail_servers_metadata_gin ON messaging.mail_servers USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_mail_servers_metadata_deleted_at ON messaging.mail_servers ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_mail_servers_metadata_created_at ON messaging.mail_servers ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_mail_servers_metadata_updated_at ON messaging.mail_servers ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION messaging.mail_servers_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS mail_servers_insert_audit ON messaging.mail_servers;
CREATE TRIGGER mail_servers_insert_audit BEFORE INSERT ON messaging.mail_servers
    FOR EACH ROW EXECUTE FUNCTION messaging.mail_servers_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS mail_servers_update_audit ON messaging.mail_servers;
CREATE TRIGGER mail_servers_update_audit BEFORE UPDATE ON messaging.mail_servers
    FOR EACH ROW EXECUTE FUNCTION messaging.mail_servers_audit_timestamp();
