-- Migration: Create mail_message_reactions table
-- Generated by metaphor-schema

CREATE SCHEMA IF NOT EXISTS messaging;

CREATE TABLE IF NOT EXISTS messaging.mail_message_reactions (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    message_id UUID NOT NULL,
    content TEXT NOT NULL,
    partner_id UUID,
    guest_id UUID,
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE UNIQUE INDEX IF NOT EXISTS mail_reaction_partner_uniq ON messaging.mail_message_reactions (message_id, partner_id, content) WHERE partner_id IS NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS mail_reaction_guest_uniq ON messaging.mail_message_reactions (message_id, guest_id, content) WHERE guest_id IS NOT NULL;

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_mail_message_reactions_metadata_gin ON messaging.mail_message_reactions USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_mail_message_reactions_metadata_deleted_at ON messaging.mail_message_reactions ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_mail_message_reactions_metadata_created_at ON messaging.mail_message_reactions ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_mail_message_reactions_metadata_updated_at ON messaging.mail_message_reactions ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION messaging.mail_message_reactions_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS mail_message_reactions_insert_audit ON messaging.mail_message_reactions;
CREATE TRIGGER mail_message_reactions_insert_audit BEFORE INSERT ON messaging.mail_message_reactions
    FOR EACH ROW EXECUTE FUNCTION messaging.mail_message_reactions_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS mail_message_reactions_update_audit ON messaging.mail_message_reactions;
CREATE TRIGGER mail_message_reactions_update_audit BEFORE UPDATE ON messaging.mail_message_reactions
    FOR EACH ROW EXECUTE FUNCTION messaging.mail_message_reactions_audit_timestamp();
