-- Migration: Create mail_notifications table
-- Generated by metaphor-schema

-- Create mail_notification_type enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'mail_notification_type') THEN
        CREATE TYPE mail_notification_type AS ENUM ('inbox', 'email', 'sms');
    END IF;
END
$$;

-- Create mail_notification_status enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'mail_notification_status') THEN
        CREATE TYPE mail_notification_status AS ENUM ('ready', 'process', 'pending', 'sent', 'bounce', 'exception', 'canceled');
    END IF;
END
$$;

-- Create notification_failure_type enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'notification_failure_type') THEN
        CREATE TYPE notification_failure_type AS ENUM ('mail_smtp', 'mail_email_invalid', 'mail_bounce', 'mail_blacklist', 'mail_recipient', 'mail_server', 'unknown', 'sms_number_missing', 'sms_number_format', 'sms_country_not_supported', 'sms_registration_needed', 'sms_credit', 'sms_server', 'sms_acc', 'sms_blacklist', 'sms_duplicate', 'sms_optout', 'sms_expired', 'sms_invalid_destination', 'sms_not_allowed', 'sms_not_delivered', 'sms_rejected');
    END IF;
END
$$;

CREATE SCHEMA IF NOT EXISTS messaging;

CREATE TABLE IF NOT EXISTS messaging.mail_notifications (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    mail_message_id UUID NOT NULL,
    res_partner_id UUID,
    notification_type mail_notification_type NOT NULL DEFAULT 'email',
    notification_status mail_notification_status NOT NULL DEFAULT 'ready',
    failure_type notification_failure_type,
    failure_reason TEXT,
    mail_mail_id_int UUID,
    is_read BOOLEAN NOT NULL DEFAULT FALSE,
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE UNIQUE INDEX IF NOT EXISTS mail_notification_message_partner_uniq ON messaging.mail_notifications (mail_message_id, res_partner_id) WHERE res_partner_id IS NOT NULL AND notification_type IN ('inbox','email');

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_mail_notifications_metadata_gin ON messaging.mail_notifications USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_mail_notifications_metadata_deleted_at ON messaging.mail_notifications ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_mail_notifications_metadata_created_at ON messaging.mail_notifications ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_mail_notifications_metadata_updated_at ON messaging.mail_notifications ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION messaging.mail_notifications_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS mail_notifications_insert_audit ON messaging.mail_notifications;
CREATE TRIGGER mail_notifications_insert_audit BEFORE INSERT ON messaging.mail_notifications
    FOR EACH ROW EXECUTE FUNCTION messaging.mail_notifications_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS mail_notifications_update_audit ON messaging.mail_notifications;
CREATE TRIGGER mail_notifications_update_audit BEFORE UPDATE ON messaging.mail_notifications
    FOR EACH ROW EXECUTE FUNCTION messaging.mail_notifications_audit_timestamp();
