-- Migration: Create mail_presences table
-- Generated by metaphor-schema

-- Create mail_presence_status enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'mail_presence_status') THEN
        CREATE TYPE mail_presence_status AS ENUM ('online', 'away', 'offline');
    END IF;
END
$$;

CREATE SCHEMA IF NOT EXISTS messaging;

CREATE TABLE IF NOT EXISTS messaging.mail_presences (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    user_id UUID,
    guest_id UUID,
    status mail_presence_status NOT NULL DEFAULT 'offline',
    last_poll TIMESTAMPTZ,
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE UNIQUE INDEX IF NOT EXISTS mail_presence_user_uniq ON messaging.mail_presences (user_id) WHERE user_id IS NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS mail_presence_guest_uniq ON messaging.mail_presences (guest_id) WHERE guest_id IS NOT NULL;

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_mail_presences_metadata_gin ON messaging.mail_presences USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_mail_presences_metadata_deleted_at ON messaging.mail_presences ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_mail_presences_metadata_created_at ON messaging.mail_presences ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_mail_presences_metadata_updated_at ON messaging.mail_presences ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION messaging.mail_presences_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS mail_presences_insert_audit ON messaging.mail_presences;
CREATE TRIGGER mail_presences_insert_audit BEFORE INSERT ON messaging.mail_presences
    FOR EACH ROW EXECUTE FUNCTION messaging.mail_presences_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS mail_presences_update_audit ON messaging.mail_presences;
CREATE TRIGGER mail_presences_update_audit BEFORE UPDATE ON messaging.mail_presences
    FOR EACH ROW EXECUTE FUNCTION messaging.mail_presences_audit_timestamp();
