-- Migration: Create fetchmail_servers table
-- Generated by metaphor-schema

-- Create fetchmail_state enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'fetchmail_state') THEN
        CREATE TYPE fetchmail_state AS ENUM ('draft', 'done');
    END IF;
END
$$;

CREATE SCHEMA IF NOT EXISTS messaging;

CREATE TABLE IF NOT EXISTS messaging.fetchmail_servers (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    name TEXT NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    state fetchmail_state NOT NULL DEFAULT 'draft',
    default_thread_model TEXT,
    priority INTEGER NOT NULL DEFAULT 5,
    token_hash TEXT NOT NULL,
    last_fetch_at TIMESTAMPTZ,
    error_at TIMESTAMPTZ,
    error_message TEXT,
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE UNIQUE INDEX IF NOT EXISTS fetchmail_server_token_hash_uniq ON messaging.fetchmail_servers (token_hash);

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_fetchmail_servers_metadata_gin ON messaging.fetchmail_servers USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_fetchmail_servers_metadata_deleted_at ON messaging.fetchmail_servers ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_fetchmail_servers_metadata_created_at ON messaging.fetchmail_servers ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_fetchmail_servers_metadata_updated_at ON messaging.fetchmail_servers ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION messaging.fetchmail_servers_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS fetchmail_servers_insert_audit ON messaging.fetchmail_servers;
CREATE TRIGGER fetchmail_servers_insert_audit BEFORE INSERT ON messaging.fetchmail_servers
    FOR EACH ROW EXECUTE FUNCTION messaging.fetchmail_servers_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS fetchmail_servers_update_audit ON messaging.fetchmail_servers;
CREATE TRIGGER fetchmail_servers_update_audit BEFORE UPDATE ON messaging.fetchmail_servers
    FOR EACH ROW EXECUTE FUNCTION messaging.fetchmail_servers_audit_timestamp();
