-- Migration: Create mail_activity_types table
-- Generated by metaphor-schema

-- Create mail_activity_category enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'mail_activity_category') THEN
        CREATE TYPE mail_activity_category AS ENUM ('upload_invoice', 'phonecall', 'meeting');
    END IF;
END
$$;

-- Create mail_activity_chaining_type enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'mail_activity_chaining_type') THEN
        CREATE TYPE mail_activity_chaining_type AS ENUM ('suggest', 'trigger');
    END IF;
END
$$;

-- Create mail_activity_delay_unit enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'mail_activity_delay_unit') THEN
        CREATE TYPE mail_activity_delay_unit AS ENUM ('days', 'weeks', 'months');
    END IF;
END
$$;

-- Create mail_activity_delay_from enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'mail_activity_delay_from') THEN
        CREATE TYPE mail_activity_delay_from AS ENUM ('plan_date', 'previous_activity');
    END IF;
END
$$;

CREATE SCHEMA IF NOT EXISTS messaging;

CREATE TABLE IF NOT EXISTS messaging.mail_activity_types (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    name TEXT NOT NULL,
    summary TEXT,
    note TEXT,
    category mail_activity_category,
    chaining_type mail_activity_chaining_type NOT NULL DEFAULT 'suggest',
    delay_count INTEGER NOT NULL DEFAULT 0,
    delay_unit mail_activity_delay_unit NOT NULL DEFAULT 'days',
    delay_from mail_activity_delay_from NOT NULL DEFAULT 'previous_activity',
    default_user_id UUID,
    default_note TEXT,
    icon TEXT,
    res_model TEXT,
    res_model_id UUID,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS mail_activity_type_model_idx ON messaging.mail_activity_types (res_model);

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_mail_activity_types_metadata_gin ON messaging.mail_activity_types USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_mail_activity_types_metadata_deleted_at ON messaging.mail_activity_types ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_mail_activity_types_metadata_created_at ON messaging.mail_activity_types ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_mail_activity_types_metadata_updated_at ON messaging.mail_activity_types ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION messaging.mail_activity_types_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS mail_activity_types_insert_audit ON messaging.mail_activity_types;
CREATE TRIGGER mail_activity_types_insert_audit BEFORE INSERT ON messaging.mail_activity_types
    FOR EACH ROW EXECUTE FUNCTION messaging.mail_activity_types_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS mail_activity_types_update_audit ON messaging.mail_activity_types;
CREATE TRIGGER mail_activity_types_update_audit BEFORE UPDATE ON messaging.mail_activity_types
    FOR EACH ROW EXECUTE FUNCTION messaging.mail_activity_types_audit_timestamp();
