-- Migration: Create mail_blacklists table
-- Generated by metaphor-schema

CREATE SCHEMA IF NOT EXISTS messaging;

CREATE TABLE IF NOT EXISTS messaging.mail_blacklists (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    email TEXT NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_mail_blacklists_email ON messaging.mail_blacklists (email);

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_mail_blacklists_metadata_gin ON messaging.mail_blacklists USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_mail_blacklists_metadata_deleted_at ON messaging.mail_blacklists ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_mail_blacklists_metadata_created_at ON messaging.mail_blacklists ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_mail_blacklists_metadata_updated_at ON messaging.mail_blacklists ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION messaging.mail_blacklists_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS mail_blacklists_insert_audit ON messaging.mail_blacklists;
CREATE TRIGGER mail_blacklists_insert_audit BEFORE INSERT ON messaging.mail_blacklists
    FOR EACH ROW EXECUTE FUNCTION messaging.mail_blacklists_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS mail_blacklists_update_audit ON messaging.mail_blacklists;
CREATE TRIGGER mail_blacklists_update_audit BEFORE UPDATE ON messaging.mail_blacklists
    FOR EACH ROW EXECUTE FUNCTION messaging.mail_blacklists_audit_timestamp();
