-- Migration: Create examples table
-- Generated by metaphor-schema

-- Create example_status enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'example_status') THEN
        CREATE TYPE example_status AS ENUM ('active', 'inactive');
    END IF;
END
$$;

CREATE SCHEMA IF NOT EXISTS messaging;

CREATE TABLE IF NOT EXISTS messaging.examples (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    name TEXT NOT NULL,
    description TEXT,
    status example_status NOT NULL DEFAULT 'active',
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_examples_status ON messaging.examples (status);

CREATE INDEX IF NOT EXISTS idx_examples_name ON messaging.examples (name);

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_examples_metadata_gin ON messaging.examples USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_examples_metadata_deleted_at ON messaging.examples ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_examples_metadata_created_at ON messaging.examples ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_examples_metadata_updated_at ON messaging.examples ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION messaging.examples_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS examples_insert_audit ON messaging.examples;
CREATE TRIGGER examples_insert_audit BEFORE INSERT ON messaging.examples
    FOR EACH ROW EXECUTE FUNCTION messaging.examples_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS examples_update_audit ON messaging.examples;
CREATE TRIGGER examples_update_audit BEFORE UPDATE ON messaging.examples
    FOR EACH ROW EXECUTE FUNCTION messaging.examples_audit_timestamp();
