-- Enum types for messaging module
-- Generated by metaphor-schema

-- Create mail_activity_state enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'mail_activity_state') THEN
        CREATE TYPE mail_activity_state AS ENUM ('overdue', 'today', 'planned', 'done');
    END IF;
END
$$;

-- Create mail_activity_chaining_type enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'mail_activity_chaining_type') THEN
        CREATE TYPE mail_activity_chaining_type AS ENUM ('suggest', 'trigger');
    END IF;
END
$$;

-- Create mail_activity_category enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'mail_activity_category') THEN
        CREATE TYPE mail_activity_category AS ENUM ('upload_invoice', 'phonecall', 'meeting');
    END IF;
END
$$;

-- Create mail_activity_delay_unit enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'mail_activity_delay_unit') THEN
        CREATE TYPE mail_activity_delay_unit AS ENUM ('days', 'weeks', 'months');
    END IF;
END
$$;

-- Create mail_activity_delay_from enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'mail_activity_delay_from') THEN
        CREATE TYPE mail_activity_delay_from AS ENUM ('plan_date', 'previous_activity');
    END IF;
END
$$;

-- Create mail_alias_contact enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'mail_alias_contact') THEN
        CREATE TYPE mail_alias_contact AS ENUM ('everyone', 'partners', 'followers');
    END IF;
END
$$;

-- Create mail_message_type enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'mail_message_type') THEN
        CREATE TYPE mail_message_type AS ENUM ('email', 'comment', 'notification', 'sms');
    END IF;
END
$$;

-- Create mail_state enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'mail_state') THEN
        CREATE TYPE mail_state AS ENUM ('outgoing', 'sent', 'received', 'exception', 'cancel');
    END IF;
END
$$;

-- Create mail_failure_type enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'mail_failure_type') THEN
        CREATE TYPE mail_failure_type AS ENUM ('mail_smtp', 'mail_email_invalid', 'mail_bounce', 'mail_blacklist', 'mail_recipient', 'mail_server', 'unknown');
    END IF;
END
$$;

-- Create notification_failure_type enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'notification_failure_type') THEN
        CREATE TYPE notification_failure_type AS ENUM ('mail_smtp', 'mail_email_invalid', 'mail_bounce', 'mail_blacklist', 'mail_recipient', 'mail_server', 'unknown', 'sms_number_missing', 'sms_number_format', 'sms_country_not_supported', 'sms_registration_needed', 'sms_credit', 'sms_server', 'sms_acc', 'sms_blacklist', 'sms_duplicate', 'sms_optout', 'sms_expired', 'sms_invalid_destination', 'sms_not_allowed', 'sms_not_delivered', 'sms_rejected');
    END IF;
END
$$;

-- Create mail_notification_type enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'mail_notification_type') THEN
        CREATE TYPE mail_notification_type AS ENUM ('inbox', 'email', 'sms');
    END IF;
END
$$;

-- Create mail_notification_status enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'mail_notification_status') THEN
        CREATE TYPE mail_notification_status AS ENUM ('ready', 'process', 'pending', 'sent', 'bounce', 'exception', 'canceled');
    END IF;
END
$$;

-- Create mail_moderation_status enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'mail_moderation_status') THEN
        CREATE TYPE mail_moderation_status AS ENUM ('pending', 'accepted', 'rejected_moderation');
    END IF;
END
$$;

-- Create mail_presence_status enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'mail_presence_status') THEN
        CREATE TYPE mail_presence_status AS ENUM ('online', 'away', 'offline');
    END IF;
END
$$;

-- Create discuss_channel_type enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'discuss_channel_type') THEN
        CREATE TYPE discuss_channel_type AS ENUM ('chat', 'channel', 'group');
    END IF;
END
$$;

-- Create sidebar_fold_state enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'sidebar_fold_state') THEN
        CREATE TYPE sidebar_fold_state AS ENUM ('open', 'closed');
    END IF;
END
$$;

-- Create sms_state enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'sms_state') THEN
        CREATE TYPE sms_state AS ENUM ('outgoing', 'process', 'pending', 'sent', 'error', 'canceled');
    END IF;
END
$$;

-- Create sms_failure_type enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'sms_failure_type') THEN
        CREATE TYPE sms_failure_type AS ENUM ('sms_number_missing', 'sms_number_format', 'sms_country_not_supported', 'sms_registration_needed', 'sms_credit', 'sms_server', 'sms_acc', 'sms_blacklist', 'sms_duplicate', 'sms_optout', 'unknown');
    END IF;
END
$$;

