-- Migration: Create mail_tracking_values table
-- Generated by metaphor-schema

CREATE SCHEMA IF NOT EXISTS messaging;

CREATE TABLE IF NOT EXISTS messaging.mail_tracking_values (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    mail_message_id UUID NOT NULL,
    field TEXT NOT NULL,
    field_desc TEXT,
    field_type TEXT,
    old_value_integer INTEGER,
    old_value_float DOUBLE PRECISION,
    old_value_text TEXT,
    old_value_datetime TIMESTAMPTZ,
    new_value_integer INTEGER,
    new_value_float DOUBLE PRECISION,
    new_value_text TEXT,
    new_value_datetime TIMESTAMPTZ,
    currency_id UUID,
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS mail_tracking_value_message_idx ON messaging.mail_tracking_values (mail_message_id);

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_mail_tracking_values_metadata_gin ON messaging.mail_tracking_values USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_mail_tracking_values_metadata_deleted_at ON messaging.mail_tracking_values ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_mail_tracking_values_metadata_created_at ON messaging.mail_tracking_values ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_mail_tracking_values_metadata_updated_at ON messaging.mail_tracking_values ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION messaging.mail_tracking_values_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS mail_tracking_values_insert_audit ON messaging.mail_tracking_values;
CREATE TRIGGER mail_tracking_values_insert_audit BEFORE INSERT ON messaging.mail_tracking_values
    FOR EACH ROW EXECUTE FUNCTION messaging.mail_tracking_values_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS mail_tracking_values_update_audit ON messaging.mail_tracking_values;
CREATE TRIGGER mail_tracking_values_update_audit BEFORE UPDATE ON messaging.mail_tracking_values
    FOR EACH ROW EXECUTE FUNCTION messaging.mail_tracking_values_audit_timestamp();
