//! Event handler trait for DiscussChannelMember events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::DiscussChannelMemberEvent;

/// Event handler for DiscussChannelMember events.
/// Implement this trait to react to DiscussChannelMember lifecycle events.
pub trait DiscussChannelMemberEventHandler: EventHandler<DiscussChannelMemberEvent> {}
