//! Domain events for FetchmailServer entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::FetchmailServer;

/// Domain events for FetchmailServer — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<FetchmailServer>)` variant.
pub type FetchmailServerEvent = CrudEvent<FetchmailServer>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for FetchmailServer events.
pub type FetchmailServerEventPublisher = Arc<dyn CrudEventPublisher<FetchmailServer> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopFetchmailServerEventPublisher = NoOpCrudEventPublisher<FetchmailServer>;
