//! Event handler trait for MailMessageAttachment events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::MailMessageAttachmentEvent;

/// Event handler for MailMessageAttachment events.
/// Implement this trait to react to MailMessageAttachment lifecycle events.
pub trait MailMessageAttachmentEventHandler: EventHandler<MailMessageAttachmentEvent> {}
