//! Event handler trait for MailActivityPlanTemplate events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::MailActivityPlanTemplateEvent;

/// Event handler for MailActivityPlanTemplate events.
/// Implement this trait to react to MailActivityPlanTemplate lifecycle events.
pub trait MailActivityPlanTemplateEventHandler: EventHandler<MailActivityPlanTemplateEvent> {}
