//! Domain events for MailActivityPlan entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::MailActivityPlan;

/// Domain events for MailActivityPlan — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<MailActivityPlan>)` variant.
pub type MailActivityPlanEvent = CrudEvent<MailActivityPlan>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for MailActivityPlan events.
pub type MailActivityPlanEventPublisher = Arc<dyn CrudEventPublisher<MailActivityPlan> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopMailActivityPlanEventPublisher = NoOpCrudEventPublisher<MailActivityPlan>;
