//! Domain events for MailMessageSchedule entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::MailMessageSchedule;

/// Domain events for MailMessageSchedule — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<MailMessageSchedule>)` variant.
pub type MailMessageScheduleEvent = CrudEvent<MailMessageSchedule>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for MailMessageSchedule events.
pub type MailMessageScheduleEventPublisher = Arc<dyn CrudEventPublisher<MailMessageSchedule> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopMailMessageScheduleEventPublisher = NoOpCrudEventPublisher<MailMessageSchedule>;
