//! Domain events for Mail entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::Mail;

/// Domain events for Mail — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<Mail>)` variant.
pub type MailEvent = CrudEvent<Mail>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for Mail events.
pub type MailEventPublisher = Arc<dyn CrudEventPublisher<Mail> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopMailEventPublisher = NoOpCrudEventPublisher<Mail>;
