//! Event handler trait for MailActivityType events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::MailActivityTypeEvent;

/// Event handler for MailActivityType events.
/// Implement this trait to react to MailActivityType lifecycle events.
pub trait MailActivityTypeEventHandler: EventHandler<MailActivityTypeEvent> {}
