//! Event handler trait for MailMessage events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::MailMessageEvent;

/// Event handler for MailMessage events.
/// Implement this trait to react to MailMessage lifecycle events.
pub trait MailMessageEventHandler: EventHandler<MailMessageEvent> {}
