//! Domain events for MailAttachment entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::MailAttachment;

/// Domain events for MailAttachment — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<MailAttachment>)` variant.
pub type MailAttachmentEvent = CrudEvent<MailAttachment>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for MailAttachment events.
pub type MailAttachmentEventPublisher = Arc<dyn CrudEventPublisher<MailAttachment> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopMailAttachmentEventPublisher = NoOpCrudEventPublisher<MailAttachment>;
