//! Domain events for MailActivityType entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::MailActivityType;

/// Domain events for MailActivityType — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<MailActivityType>)` variant.
pub type MailActivityTypeEvent = CrudEvent<MailActivityType>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for MailActivityType events.
pub type MailActivityTypeEventPublisher = Arc<dyn CrudEventPublisher<MailActivityType> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopMailActivityTypeEventPublisher = NoOpCrudEventPublisher<MailActivityType>;
