//! Event handler trait for MailTrackingValue events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::MailTrackingValueEvent;

/// Event handler for MailTrackingValue events.
/// Implement this trait to react to MailTrackingValue lifecycle events.
pub trait MailTrackingValueEventHandler: EventHandler<MailTrackingValueEvent> {}
