//! Domain events for MailScheduledMessage entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::MailScheduledMessage;

/// Domain events for MailScheduledMessage — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<MailScheduledMessage>)` variant.
pub type MailScheduledMessageEvent = CrudEvent<MailScheduledMessage>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for MailScheduledMessage events.
pub type MailScheduledMessageEventPublisher = Arc<dyn CrudEventPublisher<MailScheduledMessage> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopMailScheduledMessageEventPublisher = NoOpCrudEventPublisher<MailScheduledMessage>;
