//! Domain events for MailBlacklist entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::MailBlacklist;

/// Domain events for MailBlacklist — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<MailBlacklist>)` variant.
pub type MailBlacklistEvent = CrudEvent<MailBlacklist>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for MailBlacklist events.
pub type MailBlacklistEventPublisher = Arc<dyn CrudEventPublisher<MailBlacklist> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopMailBlacklistEventPublisher = NoOpCrudEventPublisher<MailBlacklist>;
