//! Event handler trait for MailGatewayAllowed events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::MailGatewayAllowedEvent;

/// Event handler for MailGatewayAllowed events.
/// Implement this trait to react to MailGatewayAllowed lifecycle events.
pub trait MailGatewayAllowedEventHandler: EventHandler<MailGatewayAllowedEvent> {}
