//! Domain events for MailTrackingValue entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::MailTrackingValue;

/// Domain events for MailTrackingValue — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<MailTrackingValue>)` variant.
pub type MailTrackingValueEvent = CrudEvent<MailTrackingValue>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for MailTrackingValue events.
pub type MailTrackingValueEventPublisher = Arc<dyn CrudEventPublisher<MailTrackingValue> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopMailTrackingValueEventPublisher = NoOpCrudEventPublisher<MailTrackingValue>;
