//! Event handler trait for MailMessageSchedule events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::MailMessageScheduleEvent;

/// Event handler for MailMessageSchedule events.
/// Implement this trait to react to MailMessageSchedule lifecycle events.
pub trait MailMessageScheduleEventHandler: EventHandler<MailMessageScheduleEvent> {}
