//! Event handler trait for Mail events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::MailEvent;

/// Event handler for Mail events.
/// Implement this trait to react to Mail lifecycle events.
pub trait MailEventHandler: EventHandler<MailEvent> {}
