//! Domain events
//!
//! Generated by metaphor-schema. Do not edit manually.

pub mod mail_activity_events;
pub mod mail_activity_event_handlers;
pub mod mail_activity_type_events;
pub mod mail_activity_type_event_handlers;
pub mod mail_activity_plan_events;
pub mod mail_activity_plan_event_handlers;
pub mod mail_activity_plan_template_events;
pub mod mail_activity_plan_template_event_handlers;
pub mod mail_alias_domain_events;
pub mod mail_alias_domain_event_handlers;
pub mod mail_alias_events;
pub mod mail_alias_event_handlers;
pub mod mail_attachment_events;
pub mod mail_attachment_event_handlers;
pub mod mail_message_attachment_events;
pub mod mail_message_attachment_event_handlers;
pub mod mail_message_star_events;
pub mod mail_message_star_event_handlers;
pub mod mail_message_events;
pub mod mail_message_event_handlers;
pub mod mail_events;
pub mod mail_event_handlers;
pub mod mail_notification_events;
pub mod mail_notification_event_handlers;
pub mod mail_message_subtype_events;
pub mod mail_message_subtype_event_handlers;
pub mod mail_message_reaction_events;
pub mod mail_message_reaction_event_handlers;
pub mod mail_followers_events;
pub mod mail_followers_event_handlers;
pub mod mail_presence_events;
pub mod mail_presence_event_handlers;
pub mod mail_blacklist_events;
pub mod mail_blacklist_event_handlers;
pub mod mail_tracking_value_events;
pub mod mail_tracking_value_event_handlers;
pub mod discuss_channel_events;
pub mod discuss_channel_event_handlers;
pub mod discuss_channel_member_events;
pub mod discuss_channel_member_event_handlers;
pub mod mail_guest_events;
pub mod mail_guest_event_handlers;
pub mod mail_server_events;
pub mod mail_server_event_handlers;
pub mod fetchmail_server_events;
pub mod fetchmail_server_event_handlers;
pub mod mail_gateway_allowed_events;
pub mod mail_gateway_allowed_event_handlers;
pub mod mail_message_schedule_events;
pub mod mail_message_schedule_event_handlers;
pub mod mail_scheduled_message_events;
pub mod mail_scheduled_message_event_handlers;
pub mod sms_events;
pub mod sms_event_handlers;
pub mod sms_template_events;
pub mod sms_template_event_handlers;
pub mod sms_tracker_events;
pub mod sms_tracker_event_handlers;

pub use mail_activity_events::{MailActivityEvent, MailActivityEventPublisher, NoopMailActivityEventPublisher};
pub use mail_activity_event_handlers::MailActivityEventHandler;
pub use mail_activity_type_events::{MailActivityTypeEvent, MailActivityTypeEventPublisher, NoopMailActivityTypeEventPublisher};
pub use mail_activity_type_event_handlers::MailActivityTypeEventHandler;
pub use mail_activity_plan_events::{MailActivityPlanEvent, MailActivityPlanEventPublisher, NoopMailActivityPlanEventPublisher};
pub use mail_activity_plan_event_handlers::MailActivityPlanEventHandler;
pub use mail_activity_plan_template_events::{MailActivityPlanTemplateEvent, MailActivityPlanTemplateEventPublisher, NoopMailActivityPlanTemplateEventPublisher};
pub use mail_activity_plan_template_event_handlers::MailActivityPlanTemplateEventHandler;
pub use mail_alias_domain_events::{MailAliasDomainEvent, MailAliasDomainEventPublisher, NoopMailAliasDomainEventPublisher};
pub use mail_alias_domain_event_handlers::MailAliasDomainEventHandler;
pub use mail_alias_events::{MailAliasEvent, MailAliasEventPublisher, NoopMailAliasEventPublisher};
pub use mail_alias_event_handlers::MailAliasEventHandler;
pub use mail_attachment_events::{MailAttachmentEvent, MailAttachmentEventPublisher, NoopMailAttachmentEventPublisher};
pub use mail_attachment_event_handlers::MailAttachmentEventHandler;
pub use mail_message_attachment_events::{MailMessageAttachmentEvent, MailMessageAttachmentEventPublisher, NoopMailMessageAttachmentEventPublisher};
pub use mail_message_attachment_event_handlers::MailMessageAttachmentEventHandler;
pub use mail_message_star_events::{MailMessageStarEvent, MailMessageStarEventPublisher, NoopMailMessageStarEventPublisher};
pub use mail_message_star_event_handlers::MailMessageStarEventHandler;
pub use mail_message_events::{MailMessageEvent, MailMessageEventPublisher, NoopMailMessageEventPublisher};
pub use mail_message_event_handlers::MailMessageEventHandler;
pub use mail_events::{MailEvent, MailEventPublisher, NoopMailEventPublisher};
pub use mail_event_handlers::MailEventHandler;
pub use mail_notification_events::{MailNotificationEvent, MailNotificationEventPublisher, NoopMailNotificationEventPublisher};
pub use mail_notification_event_handlers::MailNotificationEventHandler;
pub use mail_message_subtype_events::{MailMessageSubtypeEvent, MailMessageSubtypeEventPublisher, NoopMailMessageSubtypeEventPublisher};
pub use mail_message_subtype_event_handlers::MailMessageSubtypeEventHandler;
pub use mail_message_reaction_events::{MailMessageReactionEvent, MailMessageReactionEventPublisher, NoopMailMessageReactionEventPublisher};
pub use mail_message_reaction_event_handlers::MailMessageReactionEventHandler;
pub use mail_followers_events::{MailFollowersEvent, MailFollowersEventPublisher, NoopMailFollowersEventPublisher};
pub use mail_followers_event_handlers::MailFollowersEventHandler;
pub use mail_presence_events::{MailPresenceEvent, MailPresenceEventPublisher, NoopMailPresenceEventPublisher};
pub use mail_presence_event_handlers::MailPresenceEventHandler;
pub use mail_blacklist_events::{MailBlacklistEvent, MailBlacklistEventPublisher, NoopMailBlacklistEventPublisher};
pub use mail_blacklist_event_handlers::MailBlacklistEventHandler;
pub use mail_tracking_value_events::{MailTrackingValueEvent, MailTrackingValueEventPublisher, NoopMailTrackingValueEventPublisher};
pub use mail_tracking_value_event_handlers::MailTrackingValueEventHandler;
pub use discuss_channel_events::{DiscussChannelEvent, DiscussChannelEventPublisher, NoopDiscussChannelEventPublisher};
pub use discuss_channel_event_handlers::DiscussChannelEventHandler;
pub use discuss_channel_member_events::{DiscussChannelMemberEvent, DiscussChannelMemberEventPublisher, NoopDiscussChannelMemberEventPublisher};
pub use discuss_channel_member_event_handlers::DiscussChannelMemberEventHandler;
pub use mail_guest_events::{MailGuestEvent, MailGuestEventPublisher, NoopMailGuestEventPublisher};
pub use mail_guest_event_handlers::MailGuestEventHandler;
pub use mail_server_events::{MailServerEvent, MailServerEventPublisher, NoopMailServerEventPublisher};
pub use mail_server_event_handlers::MailServerEventHandler;
pub use fetchmail_server_events::{FetchmailServerEvent, FetchmailServerEventPublisher, NoopFetchmailServerEventPublisher};
pub use fetchmail_server_event_handlers::FetchmailServerEventHandler;
pub use mail_gateway_allowed_events::{MailGatewayAllowedEvent, MailGatewayAllowedEventPublisher, NoopMailGatewayAllowedEventPublisher};
pub use mail_gateway_allowed_event_handlers::MailGatewayAllowedEventHandler;
pub use mail_message_schedule_events::{MailMessageScheduleEvent, MailMessageScheduleEventPublisher, NoopMailMessageScheduleEventPublisher};
pub use mail_message_schedule_event_handlers::MailMessageScheduleEventHandler;
pub use mail_scheduled_message_events::{MailScheduledMessageEvent, MailScheduledMessageEventPublisher, NoopMailScheduledMessageEventPublisher};
pub use mail_scheduled_message_event_handlers::MailScheduledMessageEventHandler;
pub use sms_events::{SmsEvent, SmsEventPublisher, NoopSmsEventPublisher};
pub use sms_event_handlers::SmsEventHandler;
pub use sms_template_events::{SmsTemplateEvent, SmsTemplateEventPublisher, NoopSmsTemplateEventPublisher};
pub use sms_template_event_handlers::SmsTemplateEventHandler;
pub use sms_tracker_events::{SmsTrackerEvent, SmsTrackerEventPublisher, NoopSmsTrackerEventPublisher};
pub use sms_tracker_event_handlers::SmsTrackerEventHandler;

// <<< CUSTOM
// The bus-derived platform constants (ADR-0014 sentinel + ADR-0017 channel keys and
// the in-tx outbox stage helper). Hand-authored; declared user-owned in
// metaphor.codegen.yaml.
pub mod constants;
pub use constants::{
    bus_envelope, discuss_channel, guest_channel, partner_channel, record_channel,
    stage_bus_event, MESSAGING_PLATFORM_COMPANY_ID, OUTBOX_SCHEMA,
};
// END CUSTOM