//! Domain events for SmsTemplate entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::SmsTemplate;

/// Domain events for SmsTemplate — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<SmsTemplate>)` variant.
pub type SmsTemplateEvent = CrudEvent<SmsTemplate>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for SmsTemplate events.
pub type SmsTemplateEventPublisher = Arc<dyn CrudEventPublisher<SmsTemplate> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopSmsTemplateEventPublisher = NoOpCrudEventPublisher<SmsTemplate>;
