//! DiscussChannel seeder
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Seeds initial DiscussChannel data into the database.

use anyhow::Result;
use async_trait::async_trait;
use sqlx::PgPool;

use super::Seeder;

// ============================================================================
// DISCUSSCHANNEL SEEDER
// ============================================================================

/// Seeder for discuss_channel
pub struct SeedDiscussChannelSeeder;

impl SeedDiscussChannelSeeder {
    pub fn new() -> Self {
        Self
    }
}

impl Default for SeedDiscussChannelSeeder {
    fn default() -> Self {
        Self::new()
    }
}

#[async_trait]
impl Seeder for SeedDiscussChannelSeeder {
    fn name(&self) -> &'static str {
        "SeedDiscussChannelSeeder"
    }

    fn order(&self) -> i32 {
        18
    }

    async fn should_run(&self, pool: &PgPool) -> Result<bool> {
        // Check if messaging.discuss_channels table has any data
        let count: (i64,) = sqlx::query_as("SELECT COUNT(*) FROM messaging.discuss_channels")
            .fetch_one(pool)
            .await?;
        Ok(count.0 == 0)
    }

    async fn run(&self, pool: &PgPool) -> Result<()> {
        // Run the SQL seed file
        let sql = include_str!("../../migrations/seeds/discuss_channel_seed.sql");
        sqlx::raw_sql(sql).execute(pool).await?;
        Ok(())
    }

    async fn rollback(&self, pool: &PgPool) -> Result<()> {
        sqlx::query("DELETE FROM messaging.discuss_channels")
            .execute(pool)
            .await?;
        Ok(())
    }
}

// ============================================================================
// CUSTOM SEED DATA
// ============================================================================

// <<< CUSTOM SEED DATA START >>>
// Add custom seed data methods here
// <<< CUSTOM SEED DATA END >>>
