//! MailServer seeder
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Seeds initial MailServer data into the database.

use anyhow::Result;
use async_trait::async_trait;
use sqlx::PgPool;

use super::Seeder;

// ============================================================================
// MAILSERVER SEEDER
// ============================================================================

/// Seeder for mail_server
pub struct SeedMailServerSeeder;

impl SeedMailServerSeeder {
    pub fn new() -> Self {
        Self
    }
}

impl Default for SeedMailServerSeeder {
    fn default() -> Self {
        Self::new()
    }
}

#[async_trait]
impl Seeder for SeedMailServerSeeder {
    fn name(&self) -> &'static str {
        "SeedMailServerSeeder"
    }

    fn order(&self) -> i32 {
        21
    }

    async fn should_run(&self, pool: &PgPool) -> Result<bool> {
        // Check if messaging.mail_servers table has any data
        let count: (i64,) = sqlx::query_as("SELECT COUNT(*) FROM messaging.mail_servers")
            .fetch_one(pool)
            .await?;
        Ok(count.0 == 0)
    }

    async fn run(&self, pool: &PgPool) -> Result<()> {
        // Run the SQL seed file
        let sql = include_str!("../../migrations/seeds/mail_server_seed.sql");
        sqlx::raw_sql(sql).execute(pool).await?;
        Ok(())
    }

    async fn rollback(&self, pool: &PgPool) -> Result<()> {
        sqlx::query("DELETE FROM messaging.mail_servers")
            .execute(pool)
            .await?;
        Ok(())
    }
}

// ============================================================================
// CUSTOM SEED DATA
// ============================================================================

// <<< CUSTOM SEED DATA START >>>
// Add custom seed data methods here
// <<< CUSTOM SEED DATA END >>>
