//! MailBlacklist seeder
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Seeds initial MailBlacklist data into the database.

use anyhow::Result;
use async_trait::async_trait;
use sqlx::PgPool;

use super::Seeder;

// ============================================================================
// MAILBLACKLIST SEEDER
// ============================================================================

/// Seeder for mail_blacklist
pub struct SeedMailBlacklistSeeder;

impl SeedMailBlacklistSeeder {
    pub fn new() -> Self {
        Self
    }
}

impl Default for SeedMailBlacklistSeeder {
    fn default() -> Self {
        Self::new()
    }
}

#[async_trait]
impl Seeder for SeedMailBlacklistSeeder {
    fn name(&self) -> &'static str {
        "SeedMailBlacklistSeeder"
    }

    fn order(&self) -> i32 {
        13
    }

    async fn should_run(&self, pool: &PgPool) -> Result<bool> {
        // Check if messaging.mail_blacklists table has any data
        let count: (i64,) = sqlx::query_as("SELECT COUNT(*) FROM messaging.mail_blacklists")
            .fetch_one(pool)
            .await?;
        Ok(count.0 == 0)
    }

    async fn run(&self, pool: &PgPool) -> Result<()> {
        // Run the SQL seed file
        let sql = include_str!("../../migrations/seeds/mail_blacklist_seed.sql");
        sqlx::raw_sql(sql).execute(pool).await?;
        Ok(())
    }

    async fn rollback(&self, pool: &PgPool) -> Result<()> {
        sqlx::query("DELETE FROM messaging.mail_blacklists")
            .execute(pool)
            .await?;
        Ok(())
    }
}

// ============================================================================
// CUSTOM SEED DATA
// ============================================================================

// <<< CUSTOM SEED DATA START >>>
// Add custom seed data methods here
// <<< CUSTOM SEED DATA END >>>

