//! MailMessageAttachment seeder
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Seeds initial MailMessageAttachment data into the database.

use anyhow::Result;
use async_trait::async_trait;
use sqlx::PgPool;

use super::Seeder;

// ============================================================================
// MAILMESSAGEATTACHMENT SEEDER
// ============================================================================

/// Seeder for mail_message_attachment
pub struct SeedMailMessageAttachmentSeeder;

impl SeedMailMessageAttachmentSeeder {
    pub fn new() -> Self {
        Self
    }
}

impl Default for SeedMailMessageAttachmentSeeder {
    fn default() -> Self {
        Self::new()
    }
}

#[async_trait]
impl Seeder for SeedMailMessageAttachmentSeeder {
    fn name(&self) -> &'static str {
        "SeedMailMessageAttachmentSeeder"
    }

    fn order(&self) -> i32 {
        8
    }

    async fn should_run(&self, pool: &PgPool) -> Result<bool> {
        // Check if messaging.mail_message_attachments table has any data
        let count: (i64,) = sqlx::query_as("SELECT COUNT(*) FROM messaging.mail_message_attachments")
            .fetch_one(pool)
            .await?;
        Ok(count.0 == 0)
    }

    async fn run(&self, pool: &PgPool) -> Result<()> {
        // Run the SQL seed file
        let sql = include_str!("../../migrations/seeds/mail_message_attachment_seed.sql");
        sqlx::raw_sql(sql).execute(pool).await?;
        Ok(())
    }

    async fn rollback(&self, pool: &PgPool) -> Result<()> {
        sqlx::query("DELETE FROM messaging.mail_message_attachments")
            .execute(pool)
            .await?;
        Ok(())
    }
}

// ============================================================================
// CUSTOM SEED DATA
// ============================================================================

// <<< CUSTOM SEED DATA START >>>
// Add custom seed data methods here
// <<< CUSTOM SEED DATA END >>>

