//! SmsTracker seeder
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Seeds initial SmsTracker data into the database.

use anyhow::Result;
use async_trait::async_trait;
use sqlx::PgPool;

use super::Seeder;

// ============================================================================
// SMSTRACKER SEEDER
// ============================================================================

/// Seeder for sms_tracker
pub struct SeedSmsTrackerSeeder;

impl SeedSmsTrackerSeeder {
    pub fn new() -> Self {
        Self
    }
}

impl Default for SeedSmsTrackerSeeder {
    fn default() -> Self {
        Self::new()
    }
}

#[async_trait]
impl Seeder for SeedSmsTrackerSeeder {
    fn name(&self) -> &'static str {
        "SeedSmsTrackerSeeder"
    }

    fn order(&self) -> i32 {
        28
    }

    async fn should_run(&self, pool: &PgPool) -> Result<bool> {
        // Check if messaging.sms_trackers table has any data
        let count: (i64,) = sqlx::query_as("SELECT COUNT(*) FROM messaging.sms_trackers")
            .fetch_one(pool)
            .await?;
        Ok(count.0 == 0)
    }

    async fn run(&self, pool: &PgPool) -> Result<()> {
        // Run the SQL seed file
        let sql = include_str!("../../migrations/seeds/sms_tracker_seed.sql");
        sqlx::raw_sql(sql).execute(pool).await?;
        Ok(())
    }

    async fn rollback(&self, pool: &PgPool) -> Result<()> {
        sqlx::query("DELETE FROM messaging.sms_trackers")
            .execute(pool)
            .await?;
        Ok(())
    }
}

// ============================================================================
// CUSTOM SEED DATA
// ============================================================================

// <<< CUSTOM SEED DATA START >>>
// Add custom seed data methods here
// <<< CUSTOM SEED DATA END >>>

