//! Repository trait for MailActivityPlanTemplate aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the MailActivityPlanTemplate aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::{MailActivityPlanTemplate, MailActivityDelayUnit};

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct MailActivityPlanTemplatePaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl MailActivityPlanTemplatePaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct MailActivityPlanTemplatePaginatedResult {
    pub data: Vec<MailActivityPlanTemplate>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct MailActivityPlanTemplateFilter {
    pub plan_id: Option<Uuid>,
    pub activity_type_id: Option<Uuid>,
    pub summary: Option<String>,
    pub note: Option<String>,
    pub delay_unit: Option<MailActivityDelayUnit>,
    pub user_id: Option<Uuid>,
}

impl MailActivityPlanTemplateFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.plan_id.is_some() || self.activity_type_id.is_some() || self.summary.is_some() || self.note.is_some() || self.delay_unit.is_some() || self.user_id.is_some()
    }
}

/// Repository trait for MailActivityPlanTemplate aggregate
///
/// This trait defines the persistence contract for MailActivityPlanTemplate entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait MailActivityPlanTemplateRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new mail_activity_plan_template entity
    async fn save(&self, entity: &MailActivityPlanTemplate) -> Result<MailActivityPlanTemplate>;

    /// Find mail_activity_plan_template by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<MailActivityPlanTemplate>>;

    /// Find all mail_activity_plan_template entities
    async fn find_all(&self) -> Result<Vec<MailActivityPlanTemplate>>;

    /// Update mail_activity_plan_template by ID
    async fn update(&self, id: &str, entity: &MailActivityPlanTemplate) -> Result<Option<MailActivityPlanTemplate>>;

    /// Delete mail_activity_plan_template by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List mail_activity_plan_template with pagination
    async fn list(&self, params: MailActivityPlanTemplatePaginationParams) -> Result<MailActivityPlanTemplatePaginatedResult>;

    /// List mail_activity_plan_template with pagination and filters
    async fn list_with_filters(&self, params: MailActivityPlanTemplatePaginationParams, filters: MailActivityPlanTemplateFilter) -> Result<MailActivityPlanTemplatePaginatedResult>;

    /// Count all mail_activity_plan_template entities
    async fn count(&self) -> Result<u64>;

    /// Count mail_activity_plan_template entities matching filters
    async fn count_with_filters(&self, filters: MailActivityPlanTemplateFilter) -> Result<u64>;

    /// Check if mail_activity_plan_template exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete mail_activity_plan_template by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted mail_activity_plan_template by ID
    async fn restore(&self, id: &str) -> Result<Option<MailActivityPlanTemplate>>;

    /// List soft-deleted mail_activity_plan_template entities
    async fn list_deleted(&self, params: MailActivityPlanTemplatePaginationParams) -> Result<MailActivityPlanTemplatePaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save mail_activity_plan_template entities
    async fn bulk_save(&self, entities: &[MailActivityPlanTemplate]) -> Result<Vec<MailActivityPlanTemplate>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
