//! Repository trait for MailActivityType aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the MailActivityType aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::{MailActivityType, MailActivityCategory, MailActivityChainingType, MailActivityDelayFrom, MailActivityDelayUnit};

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct MailActivityTypePaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl MailActivityTypePaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct MailActivityTypePaginatedResult {
    pub data: Vec<MailActivityType>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct MailActivityTypeFilter {
    pub name: Option<String>,
    pub summary: Option<String>,
    pub note: Option<String>,
    pub category: Option<MailActivityCategory>,
    pub chaining_type: Option<MailActivityChainingType>,
    pub delay_unit: Option<MailActivityDelayUnit>,
    pub delay_from: Option<MailActivityDelayFrom>,
    pub default_user_id: Option<Uuid>,
    pub default_note: Option<String>,
    pub icon: Option<String>,
    pub res_model: Option<String>,
    pub res_model_id: Option<Uuid>,
    pub active: Option<bool>,
}

impl MailActivityTypeFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.name.is_some() || self.summary.is_some() || self.note.is_some() || self.category.is_some() || self.chaining_type.is_some() || self.delay_unit.is_some() || self.delay_from.is_some() || self.default_user_id.is_some() || self.default_note.is_some() || self.icon.is_some() || self.res_model.is_some() || self.res_model_id.is_some() || self.active.is_some()
    }
}

/// Repository trait for MailActivityType aggregate
///
/// This trait defines the persistence contract for MailActivityType entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait MailActivityTypeRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new mail_activity_type entity
    async fn save(&self, entity: &MailActivityType) -> Result<MailActivityType>;

    /// Find mail_activity_type by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<MailActivityType>>;

    /// Find all mail_activity_type entities
    async fn find_all(&self) -> Result<Vec<MailActivityType>>;

    /// Update mail_activity_type by ID
    async fn update(&self, id: &str, entity: &MailActivityType) -> Result<Option<MailActivityType>>;

    /// Delete mail_activity_type by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List mail_activity_type with pagination
    async fn list(&self, params: MailActivityTypePaginationParams) -> Result<MailActivityTypePaginatedResult>;

    /// List mail_activity_type with pagination and filters
    async fn list_with_filters(&self, params: MailActivityTypePaginationParams, filters: MailActivityTypeFilter) -> Result<MailActivityTypePaginatedResult>;

    /// Count all mail_activity_type entities
    async fn count(&self) -> Result<u64>;

    /// Count mail_activity_type entities matching filters
    async fn count_with_filters(&self, filters: MailActivityTypeFilter) -> Result<u64>;

    /// Check if mail_activity_type exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete mail_activity_type by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted mail_activity_type by ID
    async fn restore(&self, id: &str) -> Result<Option<MailActivityType>>;

    /// List soft-deleted mail_activity_type entities
    async fn list_deleted(&self, params: MailActivityTypePaginationParams) -> Result<MailActivityTypePaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save mail_activity_type entities
    async fn bulk_save(&self, entities: &[MailActivityType]) -> Result<Vec<MailActivityType>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
