//! Repository trait for MailActivityPlan aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the MailActivityPlan aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::MailActivityPlan;

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct MailActivityPlanPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl MailActivityPlanPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct MailActivityPlanPaginatedResult {
    pub data: Vec<MailActivityPlan>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct MailActivityPlanFilter {
    pub name: Option<String>,
    pub res_model: Option<String>,
    pub res_model_id: Option<Uuid>,
    pub active: Option<bool>,
}

impl MailActivityPlanFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.name.is_some() || self.res_model.is_some() || self.res_model_id.is_some() || self.active.is_some()
    }
}

/// Repository trait for MailActivityPlan aggregate
///
/// This trait defines the persistence contract for MailActivityPlan entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait MailActivityPlanRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new mail_activity_plan entity
    async fn save(&self, entity: &MailActivityPlan) -> Result<MailActivityPlan>;

    /// Find mail_activity_plan by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<MailActivityPlan>>;

    /// Find all mail_activity_plan entities
    async fn find_all(&self) -> Result<Vec<MailActivityPlan>>;

    /// Update mail_activity_plan by ID
    async fn update(&self, id: &str, entity: &MailActivityPlan) -> Result<Option<MailActivityPlan>>;

    /// Delete mail_activity_plan by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List mail_activity_plan with pagination
    async fn list(&self, params: MailActivityPlanPaginationParams) -> Result<MailActivityPlanPaginatedResult>;

    /// List mail_activity_plan with pagination and filters
    async fn list_with_filters(&self, params: MailActivityPlanPaginationParams, filters: MailActivityPlanFilter) -> Result<MailActivityPlanPaginatedResult>;

    /// Count all mail_activity_plan entities
    async fn count(&self) -> Result<u64>;

    /// Count mail_activity_plan entities matching filters
    async fn count_with_filters(&self, filters: MailActivityPlanFilter) -> Result<u64>;

    /// Check if mail_activity_plan exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete mail_activity_plan by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted mail_activity_plan by ID
    async fn restore(&self, id: &str) -> Result<Option<MailActivityPlan>>;

    /// List soft-deleted mail_activity_plan entities
    async fn list_deleted(&self, params: MailActivityPlanPaginationParams) -> Result<MailActivityPlanPaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save mail_activity_plan entities
    async fn bulk_save(&self, entities: &[MailActivityPlan]) -> Result<Vec<MailActivityPlan>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
