//! Repository trait for PhoneBlacklist aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the PhoneBlacklist aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;

use crate::domain::entity::PhoneBlacklist;

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct PhoneBlacklistPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl PhoneBlacklistPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct PhoneBlacklistPaginatedResult {
    pub data: Vec<PhoneBlacklist>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct PhoneBlacklistFilter {
    pub number: Option<String>,
    pub active: Option<bool>,
}

impl PhoneBlacklistFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.number.is_some() || self.active.is_some()
    }
}

/// Repository trait for PhoneBlacklist aggregate
///
/// This trait defines the persistence contract for PhoneBlacklist entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait PhoneBlacklistRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new phone_blacklist entity
    async fn save(&self, entity: &PhoneBlacklist) -> Result<PhoneBlacklist>;

    /// Find phone_blacklist by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<PhoneBlacklist>>;

    /// Find all phone_blacklist entities
    async fn find_all(&self) -> Result<Vec<PhoneBlacklist>>;

    /// Update phone_blacklist by ID
    async fn update(&self, id: &str, entity: &PhoneBlacklist) -> Result<Option<PhoneBlacklist>>;

    /// Delete phone_blacklist by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List phone_blacklist with pagination
    async fn list(&self, params: PhoneBlacklistPaginationParams) -> Result<PhoneBlacklistPaginatedResult>;

    /// List phone_blacklist with pagination and filters
    async fn list_with_filters(&self, params: PhoneBlacklistPaginationParams, filters: PhoneBlacklistFilter) -> Result<PhoneBlacklistPaginatedResult>;

    /// Count all phone_blacklist entities
    async fn count(&self) -> Result<u64>;

    /// Count phone_blacklist entities matching filters
    async fn count_with_filters(&self, filters: PhoneBlacklistFilter) -> Result<u64>;

    /// Check if phone_blacklist exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete phone_blacklist by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted phone_blacklist by ID
    async fn restore(&self, id: &str) -> Result<Option<PhoneBlacklist>>;

    /// List soft-deleted phone_blacklist entities
    async fn list_deleted(&self, params: PhoneBlacklistPaginationParams) -> Result<PhoneBlacklistPaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Query by Unique Fields
    // =========================================================================

    /// Find phone_blacklist by number
    async fn find_by_number(&self, number: &str) -> Result<Option<PhoneBlacklist>>;

    // =========================================================================
    // Existence Checks by Unique Fields
    // =========================================================================

    /// Check if phone_blacklist exists by number
    async fn exists_by_number(&self, number: &str) -> Result<bool>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save phone_blacklist entities
    async fn bulk_save(&self, entities: &[PhoneBlacklist]) -> Result<Vec<PhoneBlacklist>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
