//! Repository for MailScheduledMessage entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<MailScheduledMessage, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::PgPool;

use crate::domain::entity::MailScheduledMessage;

/// Table name for MailScheduledMessage entities
pub const TABLE_NAME: &str = "messaging.mail_scheduled_messages";

/// Repository for MailScheduledMessage entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct MailScheduledMessageRepository(
    backbone_orm::GenericCrudRepository<MailScheduledMessage, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for MailScheduledMessageRepository {
    type Target = backbone_orm::GenericCrudRepository<MailScheduledMessage, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl MailScheduledMessageRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

backbone_core::impl_crud_repository!(MailScheduledMessageRepository, MailScheduledMessage, soft_delete);
