//! Repository for MailActivityPlan entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<MailActivityPlan, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::PgPool;

use crate::domain::entity::MailActivityPlan;

/// Table name for MailActivityPlan entities
pub const TABLE_NAME: &str = "messaging.mail_activity_plans";

/// Repository for MailActivityPlan entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct MailActivityPlanRepository(
    backbone_orm::GenericCrudRepository<MailActivityPlan, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for MailActivityPlanRepository {
    type Target = backbone_orm::GenericCrudRepository<MailActivityPlan, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl MailActivityPlanRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

backbone_core::impl_crud_repository!(MailActivityPlanRepository, MailActivityPlan, soft_delete);
