//! Repository for MailAliasDomain entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<MailAliasDomain, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::PgPool;

use crate::domain::entity::MailAliasDomain;

/// Table name for MailAliasDomain entities
pub const TABLE_NAME: &str = "messaging.mail_alias_domains";

/// Repository for MailAliasDomain entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct MailAliasDomainRepository(
    backbone_orm::GenericCrudRepository<MailAliasDomain, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for MailAliasDomainRepository {
    type Target = backbone_orm::GenericCrudRepository<MailAliasDomain, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl MailAliasDomainRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

backbone_core::impl_crud_repository!(MailAliasDomainRepository, MailAliasDomain, soft_delete);
