//! Repository for MailPresence entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<MailPresence, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::PgPool;

use crate::domain::entity::MailPresence;

/// Table name for MailPresence entities
pub const TABLE_NAME: &str = "messaging.mail_presences";

/// Repository for MailPresence entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct MailPresenceRepository(
    backbone_orm::GenericCrudRepository<MailPresence, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for MailPresenceRepository {
    type Target = backbone_orm::GenericCrudRepository<MailPresence, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl MailPresenceRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

backbone_core::impl_crud_repository!(MailPresenceRepository, MailPresence, soft_delete);
