//! Repository for Mail entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<Mail, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::PgPool;

use crate::domain::entity::Mail;

/// Table name for Mail entities
pub const TABLE_NAME: &str = "messaging.mails";

/// Repository for Mail entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct MailRepository(
    backbone_orm::GenericCrudRepository<Mail, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for MailRepository {
    type Target = backbone_orm::GenericCrudRepository<Mail, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl MailRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

backbone_core::impl_crud_repository!(MailRepository, Mail, soft_delete);
