//! Repository for MailAlias entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<MailAlias, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::PgPool;

use crate::domain::entity::MailAlias;

/// Table name for MailAlias entities
pub const TABLE_NAME: &str = "messaging.mail_aliases";

/// Repository for MailAlias entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct MailAliasRepository(
    backbone_orm::GenericCrudRepository<MailAlias, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for MailAliasRepository {
    type Target = backbone_orm::GenericCrudRepository<MailAlias, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl MailAliasRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

backbone_core::impl_crud_repository!(MailAliasRepository, MailAlias, soft_delete);
