//! Repository for MailFollowers entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<MailFollowers, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::PgPool;

use crate::domain::entity::MailFollowers;

/// Table name for MailFollowers entities
pub const TABLE_NAME: &str = "messaging.mail_followers";

/// Repository for MailFollowers entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct MailFollowersRepository(
    backbone_orm::GenericCrudRepository<MailFollowers, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for MailFollowersRepository {
    type Target = backbone_orm::GenericCrudRepository<MailFollowers, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl MailFollowersRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

backbone_core::impl_crud_repository!(MailFollowersRepository, MailFollowers, soft_delete);
