//! Validator for DiscussChannel entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<DiscussChannel>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{OptionalNotBlank};
use crate::domain::entity::DiscussChannel;

/// Validator type alias for DiscussChannel entities.
pub type DiscussChannelValidator = EntityValidator<DiscussChannel>;

/// Build a validator for DiscussChannel with all schema-defined field rules.
pub fn discuss_channel_validator() -> DiscussChannelValidator {
    EntityValidator::new()
        .rule(OptionalNotBlank::new("name", |e: &DiscussChannel| e.name.as_deref()))
        .rule(OptionalNotBlank::new("description", |e: &DiscussChannel| e.description.as_deref()))
        .rule(OptionalNotBlank::new("uuid", |e: &DiscussChannel| e.uuid.as_deref()))
        .rule(OptionalNotBlank::new("default_access_mode", |e: &DiscussChannel| e.default_access_mode.as_deref()))
        .rule(OptionalNotBlank::new("avatar_128", |e: &DiscussChannel| e.avatar_128.as_deref()))
    // <<< CUSTOM RULES
    // END CUSTOM RULES
}

// <<< CUSTOM
// END CUSTOM
