//! Validator for MailActivityPlan entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<MailActivityPlan>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{OptionalNotBlank, RequiredString};
use crate::domain::entity::MailActivityPlan;

/// Validator type alias for MailActivityPlan entities.
pub type MailActivityPlanValidator = EntityValidator<MailActivityPlan>;

/// Build a validator for MailActivityPlan with all schema-defined field rules.
pub fn mail_activity_plan_validator() -> MailActivityPlanValidator {
    EntityValidator::new()
        .rule(RequiredString::new("name", |e: &MailActivityPlan| &e.name))
        .rule(OptionalNotBlank::new("res_model", |e: &MailActivityPlan| e.res_model.as_deref()))
    // <<< CUSTOM RULES
    // END CUSTOM RULES
}

// <<< CUSTOM
// END CUSTOM
