//! Validator for MailActivityPlanTemplate entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<MailActivityPlanTemplate>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{OptionalNotBlank};
use crate::domain::entity::MailActivityPlanTemplate;

/// Validator type alias for MailActivityPlanTemplate entities.
pub type MailActivityPlanTemplateValidator = EntityValidator<MailActivityPlanTemplate>;

/// Build a validator for MailActivityPlanTemplate with all schema-defined field rules.
pub fn mail_activity_plan_template_validator() -> MailActivityPlanTemplateValidator {
    EntityValidator::new()
        .rule(OptionalNotBlank::new("summary", |e: &MailActivityPlanTemplate| e.summary.as_deref()))
        .rule(OptionalNotBlank::new("note", |e: &MailActivityPlanTemplate| e.note.as_deref()))
    // <<< CUSTOM RULES
    // END CUSTOM RULES
}

// <<< CUSTOM
// END CUSTOM
