//! Validator for MailNotification entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<MailNotification>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{OptionalNotBlank};
use crate::domain::entity::MailNotification;

/// Validator type alias for MailNotification entities.
pub type MailNotificationValidator = EntityValidator<MailNotification>;

/// Build a validator for MailNotification with all schema-defined field rules.
pub fn mail_notification_validator() -> MailNotificationValidator {
    EntityValidator::new()
        .rule(OptionalNotBlank::new("failure_reason", |e: &MailNotification| e.failure_reason.as_deref()))
    // <<< CUSTOM RULES
    // hook rule: G-MAIL-7 (implement in CUSTOM zone)
    // END CUSTOM RULES
}

// <<< CUSTOM
// END CUSTOM
