//! Validator for MailAliasDomain entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<MailAliasDomain>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{OptionalNotBlank, RequiredString};
use crate::domain::entity::MailAliasDomain;

/// Validator type alias for MailAliasDomain entities.
pub type MailAliasDomainValidator = EntityValidator<MailAliasDomain>;

/// Build a validator for MailAliasDomain with all schema-defined field rules.
pub fn mail_alias_domain_validator() -> MailAliasDomainValidator {
    EntityValidator::new()
        .rule(RequiredString::new("name", |e: &MailAliasDomain| &e.name))
        .rule(OptionalNotBlank::new("catchall_alias", |e: &MailAliasDomain| e.catchall_alias.as_deref()))
        .rule(OptionalNotBlank::new("bounce_alias", |e: &MailAliasDomain| e.bounce_alias.as_deref()))
        .rule(OptionalNotBlank::new("bounce_alias_email", |e: &MailAliasDomain| e.bounce_alias_email.as_deref()))
        .rule(OptionalNotBlank::new("catchall_alias_email", |e: &MailAliasDomain| e.catchall_alias_email.as_deref()))
        .rule(OptionalNotBlank::new("from_filter", |e: &MailAliasDomain| e.from_filter.as_deref()))
    // <<< CUSTOM RULES
    // hook rule: G-MAIL-5-bounce (implement in CUSTOM zone)
    // hook rule: G-MAIL-5-catchall (implement in CUSTOM zone)
    // END CUSTOM RULES
}

// <<< CUSTOM
// END CUSTOM
