//! Validator for MailMessageStar entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<MailMessageStar>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use crate::domain::entity::MailMessageStar;

/// Validator type alias for MailMessageStar entities.
pub type MailMessageStarValidator = EntityValidator<MailMessageStar>;

/// Build a validator for MailMessageStar with all schema-defined field rules.
pub fn mail_message_star_validator() -> MailMessageStarValidator {
    EntityValidator::new()
    // <<< CUSTOM RULES
    // END CUSTOM RULES
        // No schema-derived rules — add custom rules above.
}

// <<< CUSTOM
// END CUSTOM
