//! Validator for MailActivityType entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<MailActivityType>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{OptionalNotBlank, RequiredString};
use crate::domain::entity::MailActivityType;

/// Validator type alias for MailActivityType entities.
pub type MailActivityTypeValidator = EntityValidator<MailActivityType>;

/// Build a validator for MailActivityType with all schema-defined field rules.
pub fn mail_activity_type_validator() -> MailActivityTypeValidator {
    EntityValidator::new()
        .rule(RequiredString::new("name", |e: &MailActivityType| &e.name))
        .rule(OptionalNotBlank::new("summary", |e: &MailActivityType| e.summary.as_deref()))
        .rule(OptionalNotBlank::new("note", |e: &MailActivityType| e.note.as_deref()))
        .rule(OptionalNotBlank::new("default_note", |e: &MailActivityType| e.default_note.as_deref()))
        .rule(OptionalNotBlank::new("icon", |e: &MailActivityType| e.icon.as_deref()))
        .rule(OptionalNotBlank::new("res_model", |e: &MailActivityType| e.res_model.as_deref()))
    // <<< CUSTOM RULES
    // END CUSTOM RULES
}

// <<< CUSTOM
// END CUSTOM
