//! Validator for MailMessageAttachment entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<MailMessageAttachment>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use crate::domain::entity::MailMessageAttachment;

/// Validator type alias for MailMessageAttachment entities.
pub type MailMessageAttachmentValidator = EntityValidator<MailMessageAttachment>;

/// Build a validator for MailMessageAttachment with all schema-defined field rules.
pub fn mail_message_attachment_validator() -> MailMessageAttachmentValidator {
    EntityValidator::new()
    // <<< CUSTOM RULES
    // END CUSTOM RULES
        // No schema-derived rules — add custom rules above.
}

// <<< CUSTOM
// END CUSTOM
