//! Validator for MailAlias entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<MailAlias>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{OptionalNotBlank};
use crate::domain::entity::MailAlias;

/// Validator type alias for MailAlias entities.
pub type MailAliasValidator = EntityValidator<MailAlias>;

/// Build a validator for MailAlias with all schema-defined field rules.
pub fn mail_alias_validator() -> MailAliasValidator {
    EntityValidator::new()
        .rule(OptionalNotBlank::new("alias_name", |e: &MailAlias| e.alias_name.as_deref()))
        .rule(OptionalNotBlank::new("alias_defaults", |e: &MailAlias| e.alias_defaults.as_deref()))
        .rule(OptionalNotBlank::new("alias_reply_to_address", |e: &MailAlias| e.alias_reply_to_address.as_deref()))
    // <<< CUSTOM RULES
    // END CUSTOM RULES
}

// <<< CUSTOM
// END CUSTOM
