//! Validator for MailMessageReaction entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<MailMessageReaction>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{RequiredString};
use crate::domain::entity::MailMessageReaction;

/// Validator type alias for MailMessageReaction entities.
pub type MailMessageReactionValidator = EntityValidator<MailMessageReaction>;

/// Build a validator for MailMessageReaction with all schema-defined field rules.
pub fn mail_message_reaction_validator() -> MailMessageReactionValidator {
    EntityValidator::new()
        .rule(RequiredString::new("content", |e: &MailMessageReaction| &e.content))
    // <<< CUSTOM RULES
    // END CUSTOM RULES
}

// <<< CUSTOM
// END CUSTOM
