//! Validator for Mail entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<Mail>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{OptionalNotBlank};
use crate::domain::entity::Mail;

/// Validator type alias for Mail entities.
pub type MailValidator = EntityValidator<Mail>;

/// Build a validator for Mail with all schema-defined field rules.
pub fn mail_validator() -> MailValidator {
    EntityValidator::new()
        .rule(OptionalNotBlank::new("failure_reason", |e: &Mail| e.failure_reason.as_deref()))
        .rule(OptionalNotBlank::new("email_to", |e: &Mail| e.email_to.as_deref()))
        .rule(OptionalNotBlank::new("email_cc", |e: &Mail| e.email_cc.as_deref()))
        .rule(OptionalNotBlank::new("reply_to", |e: &Mail| e.reply_to.as_deref()))
    // <<< CUSTOM RULES
    // END CUSTOM RULES
}

// <<< CUSTOM
// END CUSTOM
