//! Validator for SmsTracker entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<SmsTracker>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{OptionalNotBlank, RequiredString};
use crate::domain::entity::SmsTracker;

/// Validator type alias for SmsTracker entities.
pub type SmsTrackerValidator = EntityValidator<SmsTracker>;

/// Build a validator for SmsTracker with all schema-defined field rules.
pub fn sms_tracker_validator() -> SmsTrackerValidator {
    EntityValidator::new()
        .rule(RequiredString::new("sms_uuid", |e: &SmsTracker| &e.sms_uuid))
        .rule(OptionalNotBlank::new("failure_reason", |e: &SmsTracker| e.failure_reason.as_deref()))
        .rule(OptionalNotBlank::new("recipient", |e: &SmsTracker| e.recipient.as_deref()))
    // <<< CUSTOM RULES
    // hook rule: G-SM2 (implement in CUSTOM zone)
    // END CUSTOM RULES
}

// <<< CUSTOM
// END CUSTOM
