//! FetchmailServer API Integration Tests
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Tests the FetchmailServer CRUD API endpoints.

use chrono::Utc;
use serde_json::{json, Value};
use uuid::Uuid;

use super::crud_test_base::{CrudTestConfig, GenericCrudTest, TestDataGenerator};
use crate::integration::framework::ApiTest;
use crate::integration::helpers::CommonUtils;

// ============================================================================
// FETCHMAILSERVER TEST DATA GENERATOR
// ============================================================================

/// Test data generator for FetchmailServer
pub struct FetchmailServerTestData;

impl TestDataGenerator for FetchmailServerTestData {
    fn generate_create_payload(&self, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": Uuid::new_v4().to_string(),
            "name": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "active": false,
            "state": "draft",
            "default_thread_model": null,
            "priority": 1,
            "token_hash": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "last_fetch_at": now,
            "error_at": now,
            "error_message": null,
            "metadata": json!({}),
        })
    }

    fn generate_update_payload(&self, id: &str, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": id,
            "name": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "active": false,
            "state": "draft",
            "default_thread_model": null,
            "priority": 1,
            "token_hash": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "last_fetch_at": now,
            "error_at": now,
            "error_message": null,
            "metadata": json!({}),
        })
    }

    fn generate_invalid_payload(&self) -> Value {
        json!({
            // Missing required fields
        })
    }
}

// ============================================================================
// FETCHMAILSERVER API TEST
// ============================================================================

/// FetchmailServer API test suite
pub struct FetchmailServerApiTest {
    inner: GenericCrudTest<FetchmailServerTestData>,
}

impl FetchmailServerApiTest {
    pub fn new() -> Self {
        let mut config = CrudTestConfig::new("/api/v1/fetchmail_servers", "FetchmailServer");
        config.supports_soft_delete = true;
        Self {
            inner: GenericCrudTest::new(config, FetchmailServerTestData),
        }
    }

    pub async fn run_all(&mut self) -> Vec<crate::integration::framework::TestResult> {
        self.inner.run_all().await
    }
}

impl Default for FetchmailServerApiTest {
    fn default() -> Self {
        Self::new()
    }
}

// ============================================================================
// TESTS
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn test_fetchmail_server_crud() {
        let mut test = FetchmailServerApiTest::new();
        let results = test.run_all().await;

        for result in &results {
            println!("{:?}", result);
        }

        // Check all tests passed
        let failed: Vec<_> = results.iter().filter(|r| !r.success).collect();
        assert!(failed.is_empty(), "Some tests failed: {:?}", failed);
    }
}

// ============================================================================
// CUSTOM TESTS
// ============================================================================

// <<< CUSTOM TESTS START >>>
// Add FetchmailServer specific tests here
// <<< CUSTOM TESTS END >>>
