//! MailAlias API Integration Tests
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Tests the MailAlias CRUD API endpoints.

use chrono::Utc;
use serde_json::{json, Value};
use uuid::Uuid;

use super::crud_test_base::{CrudTestConfig, GenericCrudTest, TestDataGenerator};
use crate::integration::framework::ApiTest;
use crate::integration::helpers::CommonUtils;

// ============================================================================
// MAILALIAS TEST DATA GENERATOR
// ============================================================================

/// Test data generator for MailAlias
pub struct MailAliasTestData;

impl TestDataGenerator for MailAliasTestData {
    fn generate_create_payload(&self, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": Uuid::new_v4().to_string(),
            "alias_name": null,
            "alias_domain_id": null,
            "alias_contact": "everyone",
            "alias_model_id": null,
            "alias_parent_model_id": null,
            "alias_parent_thread_id": null,
            "alias_user_id": null,
            "alias_defaults": null,
            "alias_force_thread_id": null,
            "alias_reply_to_address": null,
            "metadata": json!({}),
        })
    }

    fn generate_update_payload(&self, id: &str, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": id,
            "alias_name": null,
            "alias_domain_id": null,
            "alias_contact": "everyone",
            "alias_model_id": null,
            "alias_parent_model_id": null,
            "alias_parent_thread_id": null,
            "alias_user_id": null,
            "alias_defaults": null,
            "alias_force_thread_id": null,
            "alias_reply_to_address": null,
            "metadata": json!({}),
        })
    }

    fn generate_invalid_payload(&self) -> Value {
        json!({
            // Missing required fields
        })
    }
}

// ============================================================================
// MAILALIAS API TEST
// ============================================================================

/// MailAlias API test suite
pub struct MailAliasApiTest {
    inner: GenericCrudTest<MailAliasTestData>,
}

impl MailAliasApiTest {
    pub fn new() -> Self {
        let mut config = CrudTestConfig::new("/api/v1/mail_aliases", "MailAlias");
        config.supports_soft_delete = true;
        Self {
            inner: GenericCrudTest::new(config, MailAliasTestData),
        }
    }

    pub async fn run_all(&mut self) -> Vec<crate::integration::framework::TestResult> {
        self.inner.run_all().await
    }
}

impl Default for MailAliasApiTest {
    fn default() -> Self {
        Self::new()
    }
}

// ============================================================================
// TESTS
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn test_mail_alias_crud() {
        let mut test = MailAliasApiTest::new();
        let results = test.run_all().await;

        for result in &results {
            println!("{:?}", result);
        }

        // Check all tests passed
        let failed: Vec<_> = results.iter().filter(|r| !r.success).collect();
        assert!(failed.is_empty(), "Some tests failed: {:?}", failed);
    }
}

// ============================================================================
// CUSTOM TESTS
// ============================================================================

// <<< CUSTOM TESTS START >>>
// Add MailAlias specific tests here
// <<< CUSTOM TESTS END >>>
