//! MailNotification API Integration Tests
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Tests the MailNotification CRUD API endpoints.

use chrono::Utc;
use serde_json::{json, Value};
use uuid::Uuid;

use super::crud_test_base::{CrudTestConfig, GenericCrudTest, TestDataGenerator};
use crate::integration::framework::ApiTest;
use crate::integration::helpers::CommonUtils;

// ============================================================================
// MAILNOTIFICATION TEST DATA GENERATOR
// ============================================================================

/// Test data generator for MailNotification
pub struct MailNotificationTestData;

impl TestDataGenerator for MailNotificationTestData {
    fn generate_create_payload(&self, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": Uuid::new_v4().to_string(),
            "mail_message_id": Uuid::new_v4().to_string(),
            "res_partner_id": null,
            "notification_type": "inbox",
            "notification_status": "ready",
            "failure_type": null,
            "failure_reason": null,
            "mail_mail_id_int": null,
            "is_read": false,
            "metadata": json!({}),
        })
    }

    fn generate_update_payload(&self, id: &str, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": id,
            "mail_message_id": Uuid::new_v4().to_string(),
            "res_partner_id": null,
            "notification_type": "inbox",
            "notification_status": "ready",
            "failure_type": null,
            "failure_reason": null,
            "mail_mail_id_int": null,
            "is_read": false,
            "metadata": json!({}),
        })
    }

    fn generate_invalid_payload(&self) -> Value {
        json!({
            // Missing required fields
        })
    }
}

// ============================================================================
// MAILNOTIFICATION API TEST
// ============================================================================

/// MailNotification API test suite
pub struct MailNotificationApiTest {
    inner: GenericCrudTest<MailNotificationTestData>,
}

impl MailNotificationApiTest {
    pub fn new() -> Self {
        let mut config = CrudTestConfig::new("/api/v1/mail_notifications", "MailNotification");
        config.supports_soft_delete = true;
        Self {
            inner: GenericCrudTest::new(config, MailNotificationTestData),
        }
    }

    pub async fn run_all(&mut self) -> Vec<crate::integration::framework::TestResult> {
        self.inner.run_all().await
    }
}

impl Default for MailNotificationApiTest {
    fn default() -> Self {
        Self::new()
    }
}

// ============================================================================
// TESTS
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn test_mail_notification_crud() {
        let mut test = MailNotificationApiTest::new();
        let results = test.run_all().await;

        for result in &results {
            println!("{:?}", result);
        }

        // Check all tests passed
        let failed: Vec<_> = results.iter().filter(|r| !r.success).collect();
        assert!(failed.is_empty(), "Some tests failed: {:?}", failed);
    }
}

// ============================================================================
// CUSTOM TESTS
// ============================================================================

// <<< CUSTOM TESTS START >>>
// Add MailNotification specific tests here
// <<< CUSTOM TESTS END >>>
