//! Mail API Integration Tests
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Tests the Mail CRUD API endpoints.

use chrono::Utc;
use serde_json::{json, Value};
use uuid::Uuid;

use super::crud_test_base::{CrudTestConfig, GenericCrudTest, TestDataGenerator};
use crate::integration::framework::ApiTest;
use crate::integration::helpers::CommonUtils;

// ============================================================================
// MAIL TEST DATA GENERATOR
// ============================================================================

/// Test data generator for Mail
pub struct MailTestData;

impl TestDataGenerator for MailTestData {
    fn generate_create_payload(&self, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": Uuid::new_v4().to_string(),
            "mail_message_id": Uuid::new_v4().to_string(),
            "state": "outgoing",
            "failure_type": null,
            "scheduled_date": null,
            "auto_delete": false,
            "failure_reason": null,
            "email_to": null,
            "email_cc": null,
            "reply_to": null,
            "headers": json!({}),
            "metadata": json!({}),
        })
    }

    fn generate_update_payload(&self, id: &str, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": id,
            "mail_message_id": Uuid::new_v4().to_string(),
            "state": "outgoing",
            "failure_type": null,
            "scheduled_date": null,
            "auto_delete": false,
            "failure_reason": null,
            "email_to": null,
            "email_cc": null,
            "reply_to": null,
            "headers": json!({}),
            "metadata": json!({}),
        })
    }

    fn generate_invalid_payload(&self) -> Value {
        json!({
            // Missing required fields
        })
    }
}

// ============================================================================
// MAIL API TEST
// ============================================================================

/// Mail API test suite
pub struct MailApiTest {
    inner: GenericCrudTest<MailTestData>,
}

impl MailApiTest {
    pub fn new() -> Self {
        let mut config = CrudTestConfig::new("/api/v1/mails", "Mail");
        config.supports_soft_delete = true;
        Self {
            inner: GenericCrudTest::new(config, MailTestData),
        }
    }

    pub async fn run_all(&mut self) -> Vec<crate::integration::framework::TestResult> {
        self.inner.run_all().await
    }
}

impl Default for MailApiTest {
    fn default() -> Self {
        Self::new()
    }
}

// ============================================================================
// TESTS
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn test_mail_crud() {
        let mut test = MailApiTest::new();
        let results = test.run_all().await;

        for result in &results {
            println!("{:?}", result);
        }

        // Check all tests passed
        let failed: Vec<_> = results.iter().filter(|r| !r.success).collect();
        assert!(failed.is_empty(), "Some tests failed: {:?}", failed);
    }
}

// ============================================================================
// CUSTOM TESTS
// ============================================================================

// <<< CUSTOM TESTS START >>>
// Add Mail specific tests here
// <<< CUSTOM TESTS END >>>
