//! Sms API Integration Tests
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Tests the Sms CRUD API endpoints.

use chrono::Utc;
use serde_json::{json, Value};
use uuid::Uuid;

use super::crud_test_base::{CrudTestConfig, GenericCrudTest, TestDataGenerator};
use crate::integration::framework::ApiTest;
use crate::integration::helpers::CommonUtils;

// ============================================================================
// SMS TEST DATA GENERATOR
// ============================================================================

/// Test data generator for Sms
pub struct SmsTestData;

impl TestDataGenerator for SmsTestData {
    fn generate_create_payload(&self, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": Uuid::new_v4().to_string(),
            "uuid": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "number": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "body": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "state": "outgoing",
            "failure_type": null,
            "error_message": null,
            "mail_message_id": null,
            "iap_status_code": null,
            "metadata": json!({}),
        })
    }

    fn generate_update_payload(&self, id: &str, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": id,
            "uuid": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "number": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "body": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "state": "outgoing",
            "failure_type": null,
            "error_message": null,
            "mail_message_id": null,
            "iap_status_code": null,
            "metadata": json!({}),
        })
    }

    fn generate_invalid_payload(&self) -> Value {
        json!({
            // Missing required fields
        })
    }
}

// ============================================================================
// SMS API TEST
// ============================================================================

/// Sms API test suite
pub struct SmsApiTest {
    inner: GenericCrudTest<SmsTestData>,
}

impl SmsApiTest {
    pub fn new() -> Self {
        let mut config = CrudTestConfig::new("/api/v1/sms", "Sms");
        config.supports_soft_delete = true;
        Self {
            inner: GenericCrudTest::new(config, SmsTestData),
        }
    }

    pub async fn run_all(&mut self) -> Vec<crate::integration::framework::TestResult> {
        self.inner.run_all().await
    }
}

impl Default for SmsApiTest {
    fn default() -> Self {
        Self::new()
    }
}

// ============================================================================
// TESTS
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn test_sms_crud() {
        let mut test = SmsApiTest::new();
        let results = test.run_all().await;

        for result in &results {
            println!("{:?}", result);
        }

        // Check all tests passed
        let failed: Vec<_> = results.iter().filter(|r| !r.success).collect();
        assert!(failed.is_empty(), "Some tests failed: {:?}", failed);
    }
}

// ============================================================================
// CUSTOM TESTS
// ============================================================================

// <<< CUSTOM TESTS START >>>
// Add Sms specific tests here
// <<< CUSTOM TESTS END >>>
