//! Mail REST handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Uses Axum and backbone-core's BackboneCrudHandler for all 12 CRUD endpoints.

use std::collections::HashMap;
use std::sync::Arc;

use axum::Router;
use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc};

// Backbone framework imports
use backbone_core::http::{ApiResponse, BackboneCrudHandler};

// Auth integration (optional)
#[cfg(feature = "auth")]
use backbone_auth::middleware::AuthContext;
#[cfg(feature = "auth")]
use backbone_auth::AuthMiddleware;

// Domain imports
use crate::domain::entity::*;
use crate::application::service::{MailService, ServiceError};

// DTO imports
use crate::presentation::dto::{CreateMailDto, UpdateMailDto, PatchMailDto, MailResponseDto};

use crate::domain::state_machine::{MailHooksState, MailHooksStateMachine, MailHooksTransition};

/// Application error type
#[derive(Debug, thiserror::Error)]
pub enum MailError {
    #[error("Not found: {0}")]
    NotFound(String),
    #[error("Validation error: {0}")]
    Validation(String),
    #[error("Database error: {0}")]
    Database(String),
    #[error("Internal error: {0}")]
    Internal(String),
}

impl From<ServiceError> for MailError {
    fn from(err: ServiceError) -> Self {
        match err {
            ServiceError::NotFound => Self::NotFound(err.to_string()),
            ServiceError::Validation(ref msg) => Self::Validation(msg.clone()),
            ServiceError::AlreadyExists(ref msg) => Self::Validation(msg.clone()),
            ServiceError::Repository(ref e) => Self::Database(e.to_string()),
            ServiceError::Internal(ref msg) => Self::Internal(msg.clone()),
        }
    }
}

impl axum::response::IntoResponse for MailError {
    fn into_response(self) -> axum::response::Response {
        use axum::http::StatusCode;
        use axum::Json;

        let (status, code) = match &self {
            Self::NotFound(_) => (StatusCode::NOT_FOUND, "MAIL_NOT_FOUND"),
            Self::Validation(_) => (StatusCode::BAD_REQUEST, "MAIL_VALIDATION_ERROR"),
            Self::Database(_) => (StatusCode::INTERNAL_SERVER_ERROR, "MAIL_DATABASE_ERROR"),
            Self::Internal(_) => (StatusCode::INTERNAL_SERVER_ERROR, "MAIL_INTERNAL_ERROR"),
        };

        let body = serde_json::json!({
            "success": false,
            "error": code,
            "message": self.to_string(),
        });

        (status, Json(body)).into_response()
    }
}

// =============================================================================
// Route Configuration
// =============================================================================

/// Create Axum router with all 16 Backbone endpoints for Mail.
///
/// # Routes
///
/// | Method | Path | Description |
/// |--------|------|-------------|
/// | GET | /mails | List with pagination |
/// | POST | /mails | Create new |
/// | GET | /mails/:id | Get by ID |
/// | PUT | /mails/:id | Full update |
/// | PATCH | /mails/:id | Partial update |
/// | DELETE | /mails/:id | Soft delete |
/// | POST | /mails/bulk | Bulk create |
/// | POST | /mails/upsert | Upsert |
/// | GET | /mails/trash | List deleted |
/// | POST | /mails/:id/restore | Restore |
/// | DELETE | /mails/empty | Empty trash |
/// | GET | /mails/:id/deleted | Get deleted by ID |
/// | DELETE | /mails/trash/:id | Permanent delete from trash |
/// | GET | /mails/count | Count active entities |
/// | GET | /mails/trash/count | Count deleted entities |
///
/// # Example
///
/// ```text
/// let service = Arc::new(MailService::with_repository(repository));
/// let router = create_mail_routes(service);
/// ```
pub fn create_mail_routes(service: Arc<MailService>) -> Router {
    BackboneCrudHandler::<MailService, Mail, CreateMailDto, UpdateMailDto, MailResponseDto>::routes(
        service,
        "/mails",
    )
}

/// Create Axum router with only the read (GET) endpoints for Mail.
///
/// Safe for public, unauthenticated exposure (e.g., reference data).
/// Mutations must be served separately via `create_mail_write_routes`,
/// typically wrapped in an auth middleware layer.
pub fn create_mail_read_routes(service: Arc<MailService>) -> Router {
    BackboneCrudHandler::<MailService, Mail, CreateMailDto, UpdateMailDto, MailResponseDto>::read_routes(
        service,
        "/mails",
    )
}

/// Create Axum router with only the write (mutation) endpoints for Mail.
///
/// These routes must NOT be publicly exposed. Wrap them with an auth
/// middleware before nesting into the application router.
///
/// # This is unguarded generic CRUD, not a validated write path
///
/// These are plain create/update/patch/delete mutations over the entity row —
/// they bypass all business invariants. If the module exposes a validated write
/// service (e.g. a command router over its domain engine), serve THAT instead
/// for any mutation that must respect domain rules.
pub fn create_mail_write_routes(service: Arc<MailService>) -> Router {
    BackboneCrudHandler::<MailService, Mail, CreateMailDto, UpdateMailDto, MailResponseDto>::write_routes(
        service,
        "/mails",
    )
}

/// Create authenticated routes with auth middleware.
///
/// Requires the `auth` feature flag. The `AuthMiddleware` implementation
/// is responsible for extracting and validating tokens, then providing
/// an `AuthContext` via request extensions.
#[cfg(feature = "auth")]
pub fn create_protected_mail_routes<A: AuthMiddleware + Send + Sync + 'static>(
    service: Arc<MailService>,
    auth: Arc<A>,
) -> Router {
    use axum::middleware;
    use axum::response::IntoResponse;

    let auth_layer = auth.clone();
    create_mail_routes(service)
        .layer(middleware::from_fn(move |mut req: axum::extract::Request, next: axum::middleware::Next| {
            let auth = auth_layer.clone();
            async move {
                let token = req.headers()
                    .get(axum::http::header::AUTHORIZATION)
                    .and_then(|h| h.to_str().ok())
                    .and_then(|raw| raw.strip_prefix("Bearer ").or_else(|| raw.strip_prefix("bearer ")))
                    .unwrap_or("");
                match auth.authenticate(token).await {
                    Ok(ctx) => {
                        req.extensions_mut().insert(ctx);
                        next.run(req).await
                    }
                    Err(_) => {
                        (axum::http::StatusCode::UNAUTHORIZED,
                         axum::Json(serde_json::json!({
                             "success": false,
                             "error": "unauthorized",
                             "message": "Authentication required"
                         }))
                        ).into_response()
                    }
                }
            }
        }))
}

// =============================================================================
// State Transition Handlers
// =============================================================================

/// Execute smtp_accepted transition on a Mail.
///
/// POST /mails/:id/transitions/smtp_accepted
pub async fn smtp_accepted_transition(
    axum::extract::State(service): axum::extract::State<Arc<MailService>>,
    axum::extract::Path(id): axum::extract::Path<String>,
    #[cfg(feature = "auth")] axum::Extension(auth): axum::Extension<AuthContext>,
) -> impl axum::response::IntoResponse {
    use axum::{http::StatusCode, Json};

    // Get current entity
    let entity = match service.get_by_id(&id).await {
        Ok(Some(e)) => e,
        Ok(None) => return (StatusCode::NOT_FOUND, Json(ApiResponse::<MailResponseDto>::not_found("Mail", &id))),
        Err(e) => return (StatusCode::INTERNAL_SERVER_ERROR, Json(ApiResponse::<MailResponseDto>::error(e.to_string()))),
    };

    // Check permission (if auth enabled)
    #[cfg(feature = "auth")]
    {
        let allowed_roles = MailHooksTransition::SmtpAccepted.allowed_roles();
        let has_specific_perm = auth.permissions.iter().any(|p| p == "mail:transition:smtp_accepted");
        let has_update_perm = auth.permissions.iter().any(|p| p == "mail:update");
        if !has_specific_perm && !has_update_perm {
            return (StatusCode::FORBIDDEN, Json(ApiResponse::<MailResponseDto>::error("Insufficient permissions for smtp_accepted transition")));
        }
    }

    // Create state machine from entity's actual status and validate transition
    let current_state: MailHooksState = entity.state.to_string().parse()
        .unwrap_or(MailHooksState::default());
    let sm = MailHooksStateMachine::from_state(current_state);
    if !sm.can_transition(MailHooksTransition::SmtpAccepted) {
        return (StatusCode::BAD_REQUEST, Json(ApiResponse::<MailResponseDto>::error("Transition not allowed from current state")));
    }

    // Apply transition via partial update
    let mut fields: HashMap<String, serde_json::Value> = HashMap::new();
    fields.insert("state".to_string(), serde_json::Value::String("Sent".to_string()));

    match service.partial_update(&id, fields).await {
        Ok(Some(updated)) => {
            let response: MailResponseDto = updated.into();
            (StatusCode::OK, Json(ApiResponse::ok(response)))
        }
        Ok(None) => (StatusCode::NOT_FOUND, Json(ApiResponse::<MailResponseDto>::not_found("Mail", &id))),
        Err(e) => (StatusCode::INTERNAL_SERVER_ERROR, Json(ApiResponse::<MailResponseDto>::error(e.to_string()))),
    }
}

/// Execute smtp_failed transition on a Mail.
///
/// POST /mails/:id/transitions/smtp_failed
pub async fn smtp_failed_transition(
    axum::extract::State(service): axum::extract::State<Arc<MailService>>,
    axum::extract::Path(id): axum::extract::Path<String>,
    #[cfg(feature = "auth")] axum::Extension(auth): axum::Extension<AuthContext>,
) -> impl axum::response::IntoResponse {
    use axum::{http::StatusCode, Json};

    // Get current entity
    let entity = match service.get_by_id(&id).await {
        Ok(Some(e)) => e,
        Ok(None) => return (StatusCode::NOT_FOUND, Json(ApiResponse::<MailResponseDto>::not_found("Mail", &id))),
        Err(e) => return (StatusCode::INTERNAL_SERVER_ERROR, Json(ApiResponse::<MailResponseDto>::error(e.to_string()))),
    };

    // Check permission (if auth enabled)
    #[cfg(feature = "auth")]
    {
        let allowed_roles = MailHooksTransition::SmtpFailed.allowed_roles();
        let has_specific_perm = auth.permissions.iter().any(|p| p == "mail:transition:smtp_failed");
        let has_update_perm = auth.permissions.iter().any(|p| p == "mail:update");
        if !has_specific_perm && !has_update_perm {
            return (StatusCode::FORBIDDEN, Json(ApiResponse::<MailResponseDto>::error("Insufficient permissions for smtp_failed transition")));
        }
    }

    // Create state machine from entity's actual status and validate transition
    let current_state: MailHooksState = entity.state.to_string().parse()
        .unwrap_or(MailHooksState::default());
    let sm = MailHooksStateMachine::from_state(current_state);
    if !sm.can_transition(MailHooksTransition::SmtpFailed) {
        return (StatusCode::BAD_REQUEST, Json(ApiResponse::<MailResponseDto>::error("Transition not allowed from current state")));
    }

    // Apply transition via partial update
    let mut fields: HashMap<String, serde_json::Value> = HashMap::new();
    fields.insert("state".to_string(), serde_json::Value::String("Exception".to_string()));

    match service.partial_update(&id, fields).await {
        Ok(Some(updated)) => {
            let response: MailResponseDto = updated.into();
            (StatusCode::OK, Json(ApiResponse::ok(response)))
        }
        Ok(None) => (StatusCode::NOT_FOUND, Json(ApiResponse::<MailResponseDto>::not_found("Mail", &id))),
        Err(e) => (StatusCode::INTERNAL_SERVER_ERROR, Json(ApiResponse::<MailResponseDto>::error(e.to_string()))),
    }
}

/// Execute inbound_acknowledged transition on a Mail.
///
/// POST /mails/:id/transitions/inbound_acknowledged
pub async fn inbound_acknowledged_transition(
    axum::extract::State(service): axum::extract::State<Arc<MailService>>,
    axum::extract::Path(id): axum::extract::Path<String>,
    #[cfg(feature = "auth")] axum::Extension(auth): axum::Extension<AuthContext>,
) -> impl axum::response::IntoResponse {
    use axum::{http::StatusCode, Json};

    // Get current entity
    let entity = match service.get_by_id(&id).await {
        Ok(Some(e)) => e,
        Ok(None) => return (StatusCode::NOT_FOUND, Json(ApiResponse::<MailResponseDto>::not_found("Mail", &id))),
        Err(e) => return (StatusCode::INTERNAL_SERVER_ERROR, Json(ApiResponse::<MailResponseDto>::error(e.to_string()))),
    };

    // Check permission (if auth enabled)
    #[cfg(feature = "auth")]
    {
        let allowed_roles = MailHooksTransition::InboundAcknowledged.allowed_roles();
        let has_specific_perm = auth.permissions.iter().any(|p| p == "mail:transition:inbound_acknowledged");
        let has_update_perm = auth.permissions.iter().any(|p| p == "mail:update");
        if !has_specific_perm && !has_update_perm {
            return (StatusCode::FORBIDDEN, Json(ApiResponse::<MailResponseDto>::error("Insufficient permissions for inbound_acknowledged transition")));
        }
    }

    // Create state machine from entity's actual status and validate transition
    let current_state: MailHooksState = entity.state.to_string().parse()
        .unwrap_or(MailHooksState::default());
    let sm = MailHooksStateMachine::from_state(current_state);
    if !sm.can_transition(MailHooksTransition::InboundAcknowledged) {
        return (StatusCode::BAD_REQUEST, Json(ApiResponse::<MailResponseDto>::error("Transition not allowed from current state")));
    }

    // Apply transition via partial update
    let mut fields: HashMap<String, serde_json::Value> = HashMap::new();
    fields.insert("state".to_string(), serde_json::Value::String("Received".to_string()));

    match service.partial_update(&id, fields).await {
        Ok(Some(updated)) => {
            let response: MailResponseDto = updated.into();
            (StatusCode::OK, Json(ApiResponse::ok(response)))
        }
        Ok(None) => (StatusCode::NOT_FOUND, Json(ApiResponse::<MailResponseDto>::not_found("Mail", &id))),
        Err(e) => (StatusCode::INTERNAL_SERVER_ERROR, Json(ApiResponse::<MailResponseDto>::error(e.to_string()))),
    }
}

/// Execute requeued transition on a Mail.
///
/// POST /mails/:id/transitions/requeued
pub async fn requeued_transition(
    axum::extract::State(service): axum::extract::State<Arc<MailService>>,
    axum::extract::Path(id): axum::extract::Path<String>,
    #[cfg(feature = "auth")] axum::Extension(auth): axum::Extension<AuthContext>,
) -> impl axum::response::IntoResponse {
    use axum::{http::StatusCode, Json};

    // Get current entity
    let entity = match service.get_by_id(&id).await {
        Ok(Some(e)) => e,
        Ok(None) => return (StatusCode::NOT_FOUND, Json(ApiResponse::<MailResponseDto>::not_found("Mail", &id))),
        Err(e) => return (StatusCode::INTERNAL_SERVER_ERROR, Json(ApiResponse::<MailResponseDto>::error(e.to_string()))),
    };

    // Check permission (if auth enabled)
    #[cfg(feature = "auth")]
    {
        let allowed_roles = MailHooksTransition::Requeued.allowed_roles();
        let has_specific_perm = auth.permissions.iter().any(|p| p == "mail:transition:requeued");
        let has_update_perm = auth.permissions.iter().any(|p| p == "mail:update");
        if !has_specific_perm && !has_update_perm {
            return (StatusCode::FORBIDDEN, Json(ApiResponse::<MailResponseDto>::error("Insufficient permissions for requeued transition")));
        }
    }

    // Create state machine from entity's actual status and validate transition
    let current_state: MailHooksState = entity.state.to_string().parse()
        .unwrap_or(MailHooksState::default());
    let sm = MailHooksStateMachine::from_state(current_state);
    if !sm.can_transition(MailHooksTransition::Requeued) {
        return (StatusCode::BAD_REQUEST, Json(ApiResponse::<MailResponseDto>::error("Transition not allowed from current state")));
    }

    // Apply transition via partial update
    let mut fields: HashMap<String, serde_json::Value> = HashMap::new();
    fields.insert("state".to_string(), serde_json::Value::String("Outgoing".to_string()));

    match service.partial_update(&id, fields).await {
        Ok(Some(updated)) => {
            let response: MailResponseDto = updated.into();
            (StatusCode::OK, Json(ApiResponse::ok(response)))
        }
        Ok(None) => (StatusCode::NOT_FOUND, Json(ApiResponse::<MailResponseDto>::not_found("Mail", &id))),
        Err(e) => (StatusCode::INTERNAL_SERVER_ERROR, Json(ApiResponse::<MailResponseDto>::error(e.to_string()))),
    }
}

/// Execute cancelled transition on a Mail.
///
/// POST /mails/:id/transitions/cancelled
pub async fn cancelled_transition(
    axum::extract::State(service): axum::extract::State<Arc<MailService>>,
    axum::extract::Path(id): axum::extract::Path<String>,
    #[cfg(feature = "auth")] axum::Extension(auth): axum::Extension<AuthContext>,
) -> impl axum::response::IntoResponse {
    use axum::{http::StatusCode, Json};

    // Get current entity
    let entity = match service.get_by_id(&id).await {
        Ok(Some(e)) => e,
        Ok(None) => return (StatusCode::NOT_FOUND, Json(ApiResponse::<MailResponseDto>::not_found("Mail", &id))),
        Err(e) => return (StatusCode::INTERNAL_SERVER_ERROR, Json(ApiResponse::<MailResponseDto>::error(e.to_string()))),
    };

    // Check permission (if auth enabled)
    #[cfg(feature = "auth")]
    {
        let allowed_roles = MailHooksTransition::Cancelled.allowed_roles();
        let has_specific_perm = auth.permissions.iter().any(|p| p == "mail:transition:cancelled");
        let has_update_perm = auth.permissions.iter().any(|p| p == "mail:update");
        if !has_specific_perm && !has_update_perm {
            return (StatusCode::FORBIDDEN, Json(ApiResponse::<MailResponseDto>::error("Insufficient permissions for cancelled transition")));
        }
    }

    // Create state machine from entity's actual status and validate transition
    let current_state: MailHooksState = entity.state.to_string().parse()
        .unwrap_or(MailHooksState::default());
    let sm = MailHooksStateMachine::from_state(current_state);
    if !sm.can_transition(MailHooksTransition::Cancelled) {
        return (StatusCode::BAD_REQUEST, Json(ApiResponse::<MailResponseDto>::error("Transition not allowed from current state")));
    }

    // Apply transition via partial update
    let mut fields: HashMap<String, serde_json::Value> = HashMap::new();
    fields.insert("state".to_string(), serde_json::Value::String("Cancel".to_string()));

    match service.partial_update(&id, fields).await {
        Ok(Some(updated)) => {
            let response: MailResponseDto = updated.into();
            (StatusCode::OK, Json(ApiResponse::ok(response)))
        }
        Ok(None) => (StatusCode::NOT_FOUND, Json(ApiResponse::<MailResponseDto>::not_found("Mail", &id))),
        Err(e) => (StatusCode::INTERNAL_SERVER_ERROR, Json(ApiResponse::<MailResponseDto>::error(e.to_string()))),
    }
}

/// Create routes for state transitions.
pub fn create_mail_transition_routes(service: Arc<MailService>) -> Router {
    use axum::routing::post;

    Router::new()
        .route("/mails/:id/transitions/smtp_accepted", post(smtp_accepted_transition))
        .route("/mails/:id/transitions/smtp_failed", post(smtp_failed_transition))
        .route("/mails/:id/transitions/inbound_acknowledged", post(inbound_acknowledged_transition))
        .route("/mails/:id/transitions/requeued", post(requeued_transition))
        .route("/mails/:id/transitions/cancelled", post(cancelled_transition))
        .with_state(service)
}
