//! HTTP handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! These handlers use Axum and backbone-core's BackboneCrudHandler
//! to provide all 12 standard Backbone CRUD endpoints.

pub mod mail_activity_handler;
pub mod mail_activity_type_handler;
pub mod mail_activity_plan_handler;
pub mod mail_activity_plan_template_handler;
pub mod mail_alias_domain_handler;
pub mod mail_alias_handler;
pub mod mail_attachment_handler;
pub mod mail_message_attachment_handler;
pub mod mail_message_star_handler;
pub mod mail_message_handler;
pub mod mail_handler;
pub mod mail_notification_handler;
pub mod mail_message_subtype_handler;
pub mod mail_message_reaction_handler;
pub mod mail_followers_handler;
pub mod mail_presence_handler;
pub mod mail_blacklist_handler;
pub mod mail_tracking_value_handler;
pub mod discuss_channel_handler;
pub mod discuss_channel_member_handler;
pub mod mail_guest_handler;
pub mod mail_server_handler;
pub mod fetchmail_server_handler;
pub mod mail_gateway_allowed_handler;
pub mod mail_message_schedule_handler;
pub mod mail_scheduled_message_handler;
pub mod sms_handler;
pub mod sms_template_handler;
pub mod sms_tracker_handler;

// <<< CUSTOM
// Increment-2 hand-written route groups (user-owned; survive regen).
pub mod thread_routes;
pub mod channel_routes;
pub mod guest_routes;
pub mod presence_routes;
pub mod attachment_routes;
pub mod webhook_routes;
pub mod public_routes;
// Increment 3 — the inbound email webhook (MAIL-M27; token consteq, bare mount).
pub mod inbound_routes;
// END CUSTOM

// Re-exports
pub use mail_activity_handler::{create_mail_activity_routes, create_mail_activity_read_routes, create_mail_activity_write_routes};
pub use mail_activity_type_handler::{create_mail_activity_type_routes, create_mail_activity_type_read_routes, create_mail_activity_type_write_routes};
pub use mail_activity_plan_handler::{create_mail_activity_plan_routes, create_mail_activity_plan_read_routes, create_mail_activity_plan_write_routes};
pub use mail_activity_plan_template_handler::{create_mail_activity_plan_template_routes, create_mail_activity_plan_template_read_routes, create_mail_activity_plan_template_write_routes};
pub use mail_alias_domain_handler::{create_mail_alias_domain_routes, create_mail_alias_domain_read_routes, create_mail_alias_domain_write_routes};
pub use mail_alias_handler::{create_mail_alias_routes, create_mail_alias_read_routes, create_mail_alias_write_routes};
pub use mail_attachment_handler::{create_mail_attachment_routes, create_mail_attachment_read_routes, create_mail_attachment_write_routes};
pub use mail_message_attachment_handler::{create_mail_message_attachment_routes, create_mail_message_attachment_read_routes, create_mail_message_attachment_write_routes};
pub use mail_message_star_handler::{create_mail_message_star_routes, create_mail_message_star_read_routes, create_mail_message_star_write_routes};
pub use mail_message_handler::{create_mail_message_routes, create_mail_message_read_routes, create_mail_message_write_routes};
pub use mail_handler::{create_mail_routes, create_mail_read_routes, create_mail_write_routes};
pub use mail_notification_handler::{create_mail_notification_routes, create_mail_notification_read_routes, create_mail_notification_write_routes};
pub use mail_message_subtype_handler::{create_mail_message_subtype_routes, create_mail_message_subtype_read_routes, create_mail_message_subtype_write_routes};
pub use mail_message_reaction_handler::{create_mail_message_reaction_routes, create_mail_message_reaction_read_routes, create_mail_message_reaction_write_routes};
pub use mail_followers_handler::{create_mail_followers_routes, create_mail_followers_read_routes, create_mail_followers_write_routes};
pub use mail_presence_handler::{create_mail_presence_routes, create_mail_presence_read_routes, create_mail_presence_write_routes};
pub use mail_blacklist_handler::{create_mail_blacklist_routes, create_mail_blacklist_read_routes, create_mail_blacklist_write_routes};
pub use mail_tracking_value_handler::{create_mail_tracking_value_routes, create_mail_tracking_value_read_routes, create_mail_tracking_value_write_routes};
pub use discuss_channel_handler::{create_discuss_channel_routes, create_discuss_channel_read_routes, create_discuss_channel_write_routes};
pub use discuss_channel_member_handler::{create_discuss_channel_member_routes, create_discuss_channel_member_read_routes, create_discuss_channel_member_write_routes};
pub use mail_guest_handler::{create_mail_guest_routes, create_mail_guest_read_routes, create_mail_guest_write_routes};
pub use mail_server_handler::{create_mail_server_routes, create_mail_server_read_routes, create_mail_server_write_routes};
pub use fetchmail_server_handler::{create_fetchmail_server_routes, create_fetchmail_server_read_routes, create_fetchmail_server_write_routes};
pub use mail_gateway_allowed_handler::{create_mail_gateway_allowed_routes, create_mail_gateway_allowed_read_routes, create_mail_gateway_allowed_write_routes};
pub use mail_message_schedule_handler::{create_mail_message_schedule_routes, create_mail_message_schedule_read_routes, create_mail_message_schedule_write_routes};
pub use mail_scheduled_message_handler::{create_mail_scheduled_message_routes, create_mail_scheduled_message_read_routes, create_mail_scheduled_message_write_routes};
pub use sms_handler::{create_sms_routes, create_sms_read_routes, create_sms_write_routes};
pub use sms_template_handler::{create_sms_template_routes, create_sms_template_read_routes, create_sms_template_write_routes};
pub use sms_tracker_handler::{create_sms_tracker_routes, create_sms_tracker_read_routes, create_sms_tracker_write_routes};
// <<< CUSTOM
// END CUSTOM