//! Sms REST handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Uses Axum and backbone-core's BackboneCrudHandler for all 12 CRUD endpoints.

use std::collections::HashMap;
use std::sync::Arc;

use axum::Router;
use serde::{Deserialize, Serialize};
use uuid::Uuid;

// Backbone framework imports
use backbone_core::http::{ApiResponse, BackboneCrudHandler};

// Auth integration (optional)
#[cfg(feature = "auth")]
use backbone_auth::middleware::AuthContext;
#[cfg(feature = "auth")]
use backbone_auth::AuthMiddleware;

// Domain imports
use crate::domain::entity::*;
use crate::application::service::{SmsService, ServiceError};

// DTO imports
use crate::presentation::dto::{CreateSmsDto, UpdateSmsDto, PatchSmsDto, SmsResponseDto};

use crate::domain::state_machine::{SmsState, SmsStateMachine, SmsTransition};

/// Application error type
#[derive(Debug, thiserror::Error)]
pub enum SmsError {
    #[error("Not found: {0}")]
    NotFound(String),
    #[error("Validation error: {0}")]
    Validation(String),
    #[error("Database error: {0}")]
    Database(String),
    #[error("Internal error: {0}")]
    Internal(String),
    // Domain-specific errors from hook rules
    #[error("sms.sms _uuid_unique — the uuid is the IAP correlation key and the tracker's link target; duplicates are rejected (fires on raw SQL in v19). Enforced by @unique on Sms.uuid.: {0}")]
    SmsUuidDuplicate(String),
}

impl From<ServiceError> for SmsError {
    fn from(err: ServiceError) -> Self {
        match err {
            ServiceError::NotFound => Self::NotFound(err.to_string()),
            ServiceError::Validation(ref msg) => Self::Validation(msg.clone()),
            ServiceError::AlreadyExists(ref msg) => Self::Validation(msg.clone()),
            ServiceError::Repository(ref e) => Self::Database(e.to_string()),
            ServiceError::Internal(ref msg) => Self::Internal(msg.clone()),
        }
    }
}

impl axum::response::IntoResponse for SmsError {
    fn into_response(self) -> axum::response::Response {
        use axum::http::StatusCode;
        use axum::Json;

        let (status, code) = match &self {
            Self::NotFound(_) => (StatusCode::NOT_FOUND, "SMS_NOT_FOUND"),
            Self::Validation(_) => (StatusCode::BAD_REQUEST, "SMS_VALIDATION_ERROR"),
            Self::Database(_) => (StatusCode::INTERNAL_SERVER_ERROR, "SMS_DATABASE_ERROR"),
            Self::Internal(_) => (StatusCode::INTERNAL_SERVER_ERROR, "SMS_INTERNAL_ERROR"),
            Self::SmsUuidDuplicate(_) => (StatusCode::UNPROCESSABLE_ENTITY, "SMS_SMS_UUID_DUPLICATE"),
        };

        let body = serde_json::json!({
            "success": false,
            "error": code,
            "message": self.to_string(),
        });

        (status, Json(body)).into_response()
    }
}

/// Domain-specific error codes for Sms
pub mod sms_errors {
    pub const SMS_UUID_DUPLICATE: &str = "SMS_SMS_UUID_DUPLICATE";
}

// =============================================================================
// Route Configuration
// =============================================================================

/// Create Axum router with all 16 Backbone endpoints for Sms.
///
/// # Routes
///
/// | Method | Path | Description |
/// |--------|------|-------------|
/// | GET | /smses | List with pagination |
/// | POST | /smses | Create new |
/// | GET | /smses/:id | Get by ID |
/// | PUT | /smses/:id | Full update |
/// | PATCH | /smses/:id | Partial update |
/// | DELETE | /smses/:id | Soft delete |
/// | POST | /smses/bulk | Bulk create |
/// | POST | /smses/upsert | Upsert |
/// | GET | /smses/trash | List deleted |
/// | POST | /smses/:id/restore | Restore |
/// | DELETE | /smses/empty | Empty trash |
/// | GET | /smses/:id/deleted | Get deleted by ID |
/// | DELETE | /smses/trash/:id | Permanent delete from trash |
/// | GET | /smses/count | Count active entities |
/// | GET | /smses/trash/count | Count deleted entities |
///
/// # Example
///
/// ```text
/// let service = Arc::new(SmsService::with_repository(repository));
/// let router = create_sms_routes(service);
/// ```
pub fn create_sms_routes(service: Arc<SmsService>) -> Router {
    BackboneCrudHandler::<SmsService, Sms, CreateSmsDto, UpdateSmsDto, SmsResponseDto>::routes(
        service,
        "/smses",
    )
}

/// Create Axum router with only the read (GET) endpoints for Sms.
///
/// Safe for public, unauthenticated exposure (e.g., reference data).
/// Mutations must be served separately via `create_sms_write_routes`,
/// typically wrapped in an auth middleware layer.
pub fn create_sms_read_routes(service: Arc<SmsService>) -> Router {
    BackboneCrudHandler::<SmsService, Sms, CreateSmsDto, UpdateSmsDto, SmsResponseDto>::read_routes(
        service,
        "/smses",
    )
}

/// Create Axum router with only the write (mutation) endpoints for Sms.
///
/// These routes must NOT be publicly exposed. Wrap them with an auth
/// middleware before nesting into the application router.
///
/// # This is unguarded generic CRUD, not a validated write path
///
/// These are plain create/update/patch/delete mutations over the entity row —
/// they bypass all business invariants. If the module exposes a validated write
/// service (e.g. a command router over its domain engine), serve THAT instead
/// for any mutation that must respect domain rules.
pub fn create_sms_write_routes(service: Arc<SmsService>) -> Router {
    BackboneCrudHandler::<SmsService, Sms, CreateSmsDto, UpdateSmsDto, SmsResponseDto>::write_routes(
        service,
        "/smses",
    )
}

/// Create authenticated routes with auth middleware.
///
/// Requires the `auth` feature flag. The `AuthMiddleware` implementation
/// is responsible for extracting and validating tokens, then providing
/// an `AuthContext` via request extensions.
#[cfg(feature = "auth")]
pub fn create_protected_sms_routes<A: AuthMiddleware + Send + Sync + 'static>(
    service: Arc<SmsService>,
    auth: Arc<A>,
) -> Router {
    use axum::middleware;
    use axum::response::IntoResponse;

    let auth_layer = auth.clone();
    create_sms_routes(service)
        .layer(middleware::from_fn(move |mut req: axum::extract::Request, next: axum::middleware::Next| {
            let auth = auth_layer.clone();
            async move {
                let token = req.headers()
                    .get(axum::http::header::AUTHORIZATION)
                    .and_then(|h| h.to_str().ok())
                    .and_then(|raw| raw.strip_prefix("Bearer ").or_else(|| raw.strip_prefix("bearer ")))
                    .unwrap_or("");
                match auth.authenticate(token).await {
                    Ok(ctx) => {
                        req.extensions_mut().insert(ctx);
                        next.run(req).await
                    }
                    Err(_) => {
                        (axum::http::StatusCode::UNAUTHORIZED,
                         axum::Json(serde_json::json!({
                             "success": false,
                             "error": "unauthorized",
                             "message": "Authentication required"
                         }))
                        ).into_response()
                    }
                }
            }
        }))
}

// =============================================================================
// State Transition Handlers
// =============================================================================

/// Execute pickup transition on a Sms.
///
/// POST /smses/:id/transitions/pickup
pub async fn pickup_transition(
    axum::extract::State(service): axum::extract::State<Arc<SmsService>>,
    axum::extract::Path(id): axum::extract::Path<String>,
    #[cfg(feature = "auth")] axum::Extension(auth): axum::Extension<AuthContext>,
) -> impl axum::response::IntoResponse {
    use axum::{http::StatusCode, Json};

    // Get current entity
    let entity = match service.get_by_id(&id).await {
        Ok(Some(e)) => e,
        Ok(None) => return (StatusCode::NOT_FOUND, Json(ApiResponse::<SmsResponseDto>::not_found("Sms", &id))),
        Err(e) => return (StatusCode::INTERNAL_SERVER_ERROR, Json(ApiResponse::<SmsResponseDto>::error(e.to_string()))),
    };

    // Check permission (if auth enabled)
    #[cfg(feature = "auth")]
    {
        let allowed_roles = SmsTransition::Pickup.allowed_roles();
        let has_specific_perm = auth.permissions.iter().any(|p| p == "sms:transition:pickup");
        let has_update_perm = auth.permissions.iter().any(|p| p == "sms:update");
        if !has_specific_perm && !has_update_perm {
            return (StatusCode::FORBIDDEN, Json(ApiResponse::<SmsResponseDto>::error("Insufficient permissions for pickup transition")));
        }
    }

    // Create state machine from entity's actual status and validate transition
    let current_state: SmsState = entity.state.to_string().parse()
        .unwrap_or(SmsState::default());
    let sm = SmsStateMachine::from_state(current_state);
    if !sm.can_transition(SmsTransition::Pickup) {
        return (StatusCode::BAD_REQUEST, Json(ApiResponse::<SmsResponseDto>::error("Transition not allowed from current state")));
    }

    // Apply transition via partial update
    let mut fields: HashMap<String, serde_json::Value> = HashMap::new();
    fields.insert("state".to_string(), serde_json::Value::String("Process".to_string()));

    match service.partial_update(&id, fields).await {
        Ok(Some(updated)) => {
            let response: SmsResponseDto = updated.into();
            (StatusCode::OK, Json(ApiResponse::ok(response)))
        }
        Ok(None) => (StatusCode::NOT_FOUND, Json(ApiResponse::<SmsResponseDto>::not_found("Sms", &id))),
        Err(e) => (StatusCode::INTERNAL_SERVER_ERROR, Json(ApiResponse::<SmsResponseDto>::error(e.to_string()))),
    }
}

/// Execute iap_accepted transition on a Sms.
///
/// POST /smses/:id/transitions/iap_accepted
pub async fn iap_accepted_transition(
    axum::extract::State(service): axum::extract::State<Arc<SmsService>>,
    axum::extract::Path(id): axum::extract::Path<String>,
    #[cfg(feature = "auth")] axum::Extension(auth): axum::Extension<AuthContext>,
) -> impl axum::response::IntoResponse {
    use axum::{http::StatusCode, Json};

    // Get current entity
    let entity = match service.get_by_id(&id).await {
        Ok(Some(e)) => e,
        Ok(None) => return (StatusCode::NOT_FOUND, Json(ApiResponse::<SmsResponseDto>::not_found("Sms", &id))),
        Err(e) => return (StatusCode::INTERNAL_SERVER_ERROR, Json(ApiResponse::<SmsResponseDto>::error(e.to_string()))),
    };

    // Check permission (if auth enabled)
    #[cfg(feature = "auth")]
    {
        let allowed_roles = SmsTransition::IapAccepted.allowed_roles();
        let has_specific_perm = auth.permissions.iter().any(|p| p == "sms:transition:iap_accepted");
        let has_update_perm = auth.permissions.iter().any(|p| p == "sms:update");
        if !has_specific_perm && !has_update_perm {
            return (StatusCode::FORBIDDEN, Json(ApiResponse::<SmsResponseDto>::error("Insufficient permissions for iap_accepted transition")));
        }
    }

    // Create state machine from entity's actual status and validate transition
    let current_state: SmsState = entity.state.to_string().parse()
        .unwrap_or(SmsState::default());
    let sm = SmsStateMachine::from_state(current_state);
    if !sm.can_transition(SmsTransition::IapAccepted) {
        return (StatusCode::BAD_REQUEST, Json(ApiResponse::<SmsResponseDto>::error("Transition not allowed from current state")));
    }

    // Apply transition via partial update
    let mut fields: HashMap<String, serde_json::Value> = HashMap::new();
    fields.insert("state".to_string(), serde_json::Value::String("Pending".to_string()));

    match service.partial_update(&id, fields).await {
        Ok(Some(updated)) => {
            let response: SmsResponseDto = updated.into();
            (StatusCode::OK, Json(ApiResponse::ok(response)))
        }
        Ok(None) => (StatusCode::NOT_FOUND, Json(ApiResponse::<SmsResponseDto>::not_found("Sms", &id))),
        Err(e) => (StatusCode::INTERNAL_SERVER_ERROR, Json(ApiResponse::<SmsResponseDto>::error(e.to_string()))),
    }
}

/// Execute delivery_confirmed transition on a Sms.
///
/// POST /smses/:id/transitions/delivery_confirmed
pub async fn delivery_confirmed_transition(
    axum::extract::State(service): axum::extract::State<Arc<SmsService>>,
    axum::extract::Path(id): axum::extract::Path<String>,
    #[cfg(feature = "auth")] axum::Extension(auth): axum::Extension<AuthContext>,
) -> impl axum::response::IntoResponse {
    use axum::{http::StatusCode, Json};

    // Get current entity
    let entity = match service.get_by_id(&id).await {
        Ok(Some(e)) => e,
        Ok(None) => return (StatusCode::NOT_FOUND, Json(ApiResponse::<SmsResponseDto>::not_found("Sms", &id))),
        Err(e) => return (StatusCode::INTERNAL_SERVER_ERROR, Json(ApiResponse::<SmsResponseDto>::error(e.to_string()))),
    };

    // Check permission (if auth enabled)
    #[cfg(feature = "auth")]
    {
        let allowed_roles = SmsTransition::DeliveryConfirmed.allowed_roles();
        let has_specific_perm = auth.permissions.iter().any(|p| p == "sms:transition:delivery_confirmed");
        let has_update_perm = auth.permissions.iter().any(|p| p == "sms:update");
        if !has_specific_perm && !has_update_perm {
            return (StatusCode::FORBIDDEN, Json(ApiResponse::<SmsResponseDto>::error("Insufficient permissions for delivery_confirmed transition")));
        }
    }

    // Create state machine from entity's actual status and validate transition
    let current_state: SmsState = entity.state.to_string().parse()
        .unwrap_or(SmsState::default());
    let sm = SmsStateMachine::from_state(current_state);
    if !sm.can_transition(SmsTransition::DeliveryConfirmed) {
        return (StatusCode::BAD_REQUEST, Json(ApiResponse::<SmsResponseDto>::error("Transition not allowed from current state")));
    }

    // Apply transition via partial update
    let mut fields: HashMap<String, serde_json::Value> = HashMap::new();
    fields.insert("state".to_string(), serde_json::Value::String("Sent".to_string()));

    match service.partial_update(&id, fields).await {
        Ok(Some(updated)) => {
            let response: SmsResponseDto = updated.into();
            (StatusCode::OK, Json(ApiResponse::ok(response)))
        }
        Ok(None) => (StatusCode::NOT_FOUND, Json(ApiResponse::<SmsResponseDto>::not_found("Sms", &id))),
        Err(e) => (StatusCode::INTERNAL_SERVER_ERROR, Json(ApiResponse::<SmsResponseDto>::error(e.to_string()))),
    }
}

/// Execute send_failed transition on a Sms.
///
/// POST /smses/:id/transitions/send_failed
pub async fn send_failed_transition(
    axum::extract::State(service): axum::extract::State<Arc<SmsService>>,
    axum::extract::Path(id): axum::extract::Path<String>,
    #[cfg(feature = "auth")] axum::Extension(auth): axum::Extension<AuthContext>,
) -> impl axum::response::IntoResponse {
    use axum::{http::StatusCode, Json};

    // Get current entity
    let entity = match service.get_by_id(&id).await {
        Ok(Some(e)) => e,
        Ok(None) => return (StatusCode::NOT_FOUND, Json(ApiResponse::<SmsResponseDto>::not_found("Sms", &id))),
        Err(e) => return (StatusCode::INTERNAL_SERVER_ERROR, Json(ApiResponse::<SmsResponseDto>::error(e.to_string()))),
    };

    // Check permission (if auth enabled)
    #[cfg(feature = "auth")]
    {
        let allowed_roles = SmsTransition::SendFailed.allowed_roles();
        let has_specific_perm = auth.permissions.iter().any(|p| p == "sms:transition:send_failed");
        let has_update_perm = auth.permissions.iter().any(|p| p == "sms:update");
        if !has_specific_perm && !has_update_perm {
            return (StatusCode::FORBIDDEN, Json(ApiResponse::<SmsResponseDto>::error("Insufficient permissions for send_failed transition")));
        }
    }

    // Create state machine from entity's actual status and validate transition
    let current_state: SmsState = entity.state.to_string().parse()
        .unwrap_or(SmsState::default());
    let sm = SmsStateMachine::from_state(current_state);
    if !sm.can_transition(SmsTransition::SendFailed) {
        return (StatusCode::BAD_REQUEST, Json(ApiResponse::<SmsResponseDto>::error("Transition not allowed from current state")));
    }

    // Apply transition via partial update
    let mut fields: HashMap<String, serde_json::Value> = HashMap::new();
    fields.insert("state".to_string(), serde_json::Value::String("Error".to_string()));

    match service.partial_update(&id, fields).await {
        Ok(Some(updated)) => {
            let response: SmsResponseDto = updated.into();
            (StatusCode::OK, Json(ApiResponse::ok(response)))
        }
        Ok(None) => (StatusCode::NOT_FOUND, Json(ApiResponse::<SmsResponseDto>::not_found("Sms", &id))),
        Err(e) => (StatusCode::INTERNAL_SERVER_ERROR, Json(ApiResponse::<SmsResponseDto>::error(e.to_string()))),
    }
}

/// Execute canceled transition on a Sms.
///
/// POST /smses/:id/transitions/canceled
pub async fn canceled_transition(
    axum::extract::State(service): axum::extract::State<Arc<SmsService>>,
    axum::extract::Path(id): axum::extract::Path<String>,
    #[cfg(feature = "auth")] axum::Extension(auth): axum::Extension<AuthContext>,
) -> impl axum::response::IntoResponse {
    use axum::{http::StatusCode, Json};

    // Get current entity
    let entity = match service.get_by_id(&id).await {
        Ok(Some(e)) => e,
        Ok(None) => return (StatusCode::NOT_FOUND, Json(ApiResponse::<SmsResponseDto>::not_found("Sms", &id))),
        Err(e) => return (StatusCode::INTERNAL_SERVER_ERROR, Json(ApiResponse::<SmsResponseDto>::error(e.to_string()))),
    };

    // Check permission (if auth enabled)
    #[cfg(feature = "auth")]
    {
        let allowed_roles = SmsTransition::Canceled.allowed_roles();
        let has_specific_perm = auth.permissions.iter().any(|p| p == "sms:transition:canceled");
        let has_update_perm = auth.permissions.iter().any(|p| p == "sms:update");
        if !has_specific_perm && !has_update_perm {
            return (StatusCode::FORBIDDEN, Json(ApiResponse::<SmsResponseDto>::error("Insufficient permissions for canceled transition")));
        }
    }

    // Create state machine from entity's actual status and validate transition
    let current_state: SmsState = entity.state.to_string().parse()
        .unwrap_or(SmsState::default());
    let sm = SmsStateMachine::from_state(current_state);
    if !sm.can_transition(SmsTransition::Canceled) {
        return (StatusCode::BAD_REQUEST, Json(ApiResponse::<SmsResponseDto>::error("Transition not allowed from current state")));
    }

    // Apply transition via partial update
    let mut fields: HashMap<String, serde_json::Value> = HashMap::new();
    fields.insert("state".to_string(), serde_json::Value::String("Canceled".to_string()));

    match service.partial_update(&id, fields).await {
        Ok(Some(updated)) => {
            let response: SmsResponseDto = updated.into();
            (StatusCode::OK, Json(ApiResponse::ok(response)))
        }
        Ok(None) => (StatusCode::NOT_FOUND, Json(ApiResponse::<SmsResponseDto>::not_found("Sms", &id))),
        Err(e) => (StatusCode::INTERNAL_SERVER_ERROR, Json(ApiResponse::<SmsResponseDto>::error(e.to_string()))),
    }
}

/// Create routes for state transitions.
pub fn create_sms_transition_routes(service: Arc<SmsService>) -> Router {
    use axum::routing::post;

    Router::new()
        .route("/smses/:id/transitions/pickup", post(pickup_transition))
        .route("/smses/:id/transitions/iap_accepted", post(iap_accepted_transition))
        .route("/smses/:id/transitions/delivery_confirmed", post(delivery_confirmed_transition))
        .route("/smses/:id/transitions/send_failed", post(send_failed_transition))
        .route("/smses/:id/transitions/canceled", post(canceled_transition))
        .with_state(service)
}

